### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by Lewy-H** [nbrightproject/NBrightBuy#1]
Hi I have tried downloading the zip for the project and installing through the 'Install extension wizard' but get the critical error: Could not find file 'C:\inetpub\vsites\DEVELOPMENT SITES\NBStore\Install\Temp\yhbl2fou\NBS.dnn'.

I then extracted the zip and rezipped the contents of the NBrightBuy-master folder, tried again and got the same error.

I can see the file in the installation folder but I don't know what I am doing wrong, could you advise?

**Comment by leedavi** [comment]
The download on this site is for the source, not the install package.  For the install package you'll need to download from the DNN Store.

http://store.dnnsoftware.com/home/product-details/nbsv3-nb-store-open-source-ecommerce

also have a read on this.

http://nbsdocs.nbrightproject.org/Documentation/Integratorguide/Installation.aspx

It's a little out of date with the links, because of the move away from codeplex, but the principle is the same.

**Comment by Lewy-H** [comment]
OK thanks a lot. You should know then that the link to the DNN store page on the website here http://www.nbrightproject.org/#download is broken, which is what brought me here.

**Comment by leedavi** [comment]
Ah!.. OK Thx.. I changed the name to make it reference in the DNN Store better.. forgot the link.

**Comment by Lewy-H** [comment]
Where is the best place for me to submit issues with installing because I feel like this isn't the right place?

I just went through the integration guide up until the template install. After which I was automatically directed to the back office. The problem I am now having is that the back office is set as my home page and I can't access the site from any other browser that I am not logged in already on.

Do you have any ideas what has caused this? I have performed all of the installation on a fresh install of the latest DNN.

**Comment by leedavi** [comment]
Did you change the DNN skin or the skin of the home page?

The idea is to create a DNN Page for the BO and only change that page skin, Not the whole DNN website skin..... is that what you have done?

Try typing in    htpp://<you domain>/Admin/SiteSettings.aspx

does that bring up the site setting or the NBS BO?

**Comment by Lewy-H** [comment]
I went to the site wizard from the Admin section and selected the template and followed it through selecting the NBS options. Then I ended up in the back office. Every page now just shows the back office basically.

**Comment by Lewy-H** [comment]
I fixed the issue by temporarily removing the NBrightBuy.dll from the bin, then going in to Admin > Themes and restoring to default, then including the NBrightBuy.dll again. The Back Office still seems to be themed properly.

I'm not sure if this is something I did wrong, or with the template install itself but it's worth looking into.

**Comment by leedavi** [comment]
OK, thx.  I'll try and re-create.  Can't think what could cause it, unless that template set the admin theme to the Bo skin... but if that was the case, I wouldn't have even been able to create the export template, everything would have been the BO, like you found.

Very Odd, What version of DNN was this?

**Comment by Lewy-H** [comment]
I have been using the latest DNN 07.04.01. I have followed the steps outlines here http://nbsdocs.nbrightproject.org/Documentation/Integratorguide/Installation.aspx and I am now having a few more issues with the image thumbnail not showing up on the product page, and products not displaying in the productview module.

I also can't seem to edit a product once I have created it. When I click on the pencil icon next to the product, I get taken to the product page but there is no editing functionality.

I take it then that this isn't currently a stable version suitable for use?

**Comment by leedavi** [comment]
It Is stable, but the setup on that template is very basic and probably not what you would release directly to a client.
That pen on the product list is being covered by the template css, I saw that the other day, the template needs to be updated, so you can edit from there.  Currently you'll need to go into the BO and edit directly from there.

Not sure about the thumbnail not working... can I see you site on the internet?

**Comment by Lewy-H** [comment]
The development site is http://nbstore.pmits.co.uk/. Here is the product that isn't showing up http://nbstore.pmits.co.uk/Home/eid/25/ctrl/products. The css seems a little off on the product page, is there a skin I was supposed to install or that you would recommend?

The thumbnail seems broken because of this string '&w={Settings' at the end. Maybe missed off the closing bracket somewhere?

Is there any reason that the product wouldn't be showing on the product list? I really like the demo sites and want to get this working but I can't spend too long on fixing bugs as I'm stuck between deciding to modify something we've already started, or starting from scratch with this.

Is the edit product button supposed to stay in BO or redirect to the product page with editing options?

I could pass you a log-in to the site privately if you wish to have a look at the BO.

**Comment by leedavi** [comment]
looks like your module settings or display template is corrupt.  Try going into the module setting and resaving.  If that doesn't work send me a login to dcl@  nevoweb .com and I'll have a look

**Comment by Lewy-H** [comment]
Tried saving but no difference. Just sent over the credentials.

**Comment by leedavi** [comment]
OK it's working, I just needed to go into the BO>Admin>Settings and save again and then go into the module settings and resave (There is a double save required when you change the theme, need to get a fix for that).  I've never seen that edit button going to the product list before, I'm unsure how you did that :-)

**Comment by Lewy-H** [comment]
Well that looks a lot better, thank you! Are there any options for advanced pricing rules for particular customers to give discounts based on users or roles?

**Comment by leedavi** [comment]
There's only a dealer roles for special price, client level discount codes and a normal sale price ATM.  the full promotions plugin is under development.

**Comment by Lewy-H** [comment]
Any idea when it will be out?

**Comment by leedavi** [comment]
I'd like to say tomorrow, but in truth it's going to be longer.  I do have a client waiting for this, so my hope is we'll get it finished within 2 months.

**Comment by Lewy-H** [comment]
Not having the ability to set discounts or price rules is the only reason I won't be able to go ahead with this product which is a shame because I really like the UI. 

Is there any way I could be notified when the plug-in becomes available? What sort of pricing rules are you working towards; buy 3 get 20% off, customer / role based discounts?
