### ISSUE TITLE
Can not install Extension Could not find file NBS.dnn

### ISSUE THREAD

**Issue by CPQcart** [nbrightproject/NBrightBuy#10]
I get error message
Message:Could not find file 'D:\Development\DevNBrightBuy\Install\Temp\0t4bkrxb\NBS.dnn'.
It is there in dir listed below
D:\Development\DevNBrightBuy\Install\Temp\0t4bkrxb\NBrightBuy-master\Installation

I have Unblocked the downloaded ZIP

It occurs from my desktop and on the dedicated server.

Thanks in advance for any help

**Comment by leedavi** [comment]
I think your trying to install the source from GitHub as a module, this won't work, it's the dev source you get from here, not the install module.

Look at these instructions:

http://nbsdocs.nbrightproject.org/Documentation/Integratorguide/Installation.aspx
