### ISSUE TITLE
Featured Products in Razor Templates

### ISSUE THREAD

**Issue by qualitymanager** [nbrightproject/NBrightBuy#100]
The previous version of nbstore had a checkbox for featured products, when ticked you could configure the productdisplay module to display those featured produts, but the checkbox for "featured" is missing from the backoffice.

Does this new version not have this feature anymore? 
If it does, can you give me an example of the required backoffice and productlist module configuration settings?

**Comment by leedavi** [comment]
The functionality has been built into the properties options.

Go into BO>Catalog>properties and create a new property under featured group.

You can then assign this property to a product.

Using the product display module, make it a static module list using the feature property you created.
