### ISSUE TITLE
CheckOut Failures

### ISSUE THREAD

**Issue by 3wiggle** [nbrightproject/NBrightBuy#101]
New Install (dnn 8 and nBrightBuy)... could not get past buyer address validations for Email and PostalCode.. ALWAYS displayed red asterisk even with valid data in either/both. 

Downloaded and successfully BUILT current master from here... thinking fixes may be in place but have exactly the same behavior... searching code now... any suggestions will be greatly appreciated.

Interesting to note that Country DropDown list is empty????? may be related...

ALSO, unable to attach/upload product images?  (errr, just thought... I am remote session into dedicated server... should test from remote client... if that makes any difference...)

I am a long standing NBS user, (with several customizations) ... upgrading clients and truly need this Operational soon.

**Comment by micahsdad1402** [comment]
I'm pretty sure this is in the setup instructions.
You need to go to the store admin, settings, country details, and select the countries you are going to use. You can do this in such a way as the common ones that you use will be at the top if you select them all. I suspect this will resolve your problem.

**Comment by 3wiggle** [comment]
Thanks John... You are correct this requirement is in the getting started instructions... BUT I would swear in court  that it was not there first time I went through ... LOL
