### ISSUE TITLE
Add to Cart & Buy Now disappeared?

### ISSUE THREAD

**Issue by 3wiggle** [nbrightproject/NBrightBuy#104]
I have spent two days trying to figure out where the add to cart (OnLine Shop) and But Now (Details) went... I processed ONE product one time through the checkout... ever since I am unable to add anything to cart... I have added second and third items ... but nothing display either button.... ????

**Comment by leedavi** [comment]
I've never heard of this before, the only code to stop the buy button appearing is on the product list if the product has multiple models and therefore forces the client to go to the detail page to purchase.

can I see this store on-line?

**Comment by 3wiggle** [comment]
Thank You

**Comment by leedavi** [comment]
You had catalog mode on in the BO>Admin>Settings.  This turns off the buy button.

I've change it now.  I suggest you alter the host password, you should post them on a open forum.

GitHub is not good with the, we're working on moving to a real forum so we can pass PM easier.

**Comment by 3wiggle** [comment]
Catalog mode... do not remember toggling that... must have been an experiment... Never thought it would present a catalog without option to buy... but thanks...

PS:  that password was temporary... as well as use of HOST as name on site... I agree never should post but in this case I had no idea where you needed to get... AND this is truly just a LAB Exercise before building production ...

Thanks again..
