### ISSUE TITLE
Upgrade from Nbright 3.1.14 to latest razor version 

### ISSUE THREAD

**Issue by rogerg1967** [nbrightproject/NBrightBuy#105]
Hi,
i am trying to resolve some issues with a previous version of NBright Store 3.1.14 which is prior to the Razor    
Upgrade to the latest version. can you advise if I can do a straight upgrade or will my old install stop working?

**Comment by leedavi** [comment]
Hi,

You can upgrade, but it's not stright forward.  I've created a document here.

http://nbsdocs.nbrightproject.org/Documentation/Downloads

The latest version also replaces the ProductSearch module with DisplaySearch module, so you'll need to remove that and add the new one.

Also, we have a new forum, can you post question on there please. 

http://forum.nbrightproject.org/
