### ISSUE TITLE
New Install stuck in 

### ISSUE THREAD

**Issue by CPQcart** [nbrightproject/NBrightBuy#11]
Installed with Site Wizard new DNN site used nbs-example-setup.template
per http://nbsdocs.nbrightproject.org/Documentation/Integratorguide/Installation.aspx
Installed 
34794_0_NBrightDNN_TemplateSys_v03.03.00.zip
34794_0_NBrightStore_03.01.00.00_Install.zip
Only installed the higher version of like names
With Site Wizard run again using nbs-example-setup.template
that takes me info myURL/Home/ctrl/settings
I have SET Store Configuration> Back Office Exit Page=Home
change & Save Back Office Exit Page=Basket still goes into myURL//Basket
I only have db's = NBrightBuy , NBrightBuyIdx , NBrightBuyLang , NBrightData

I can not do the next step as hung in Exit not working
After creating the site structure with the DNN wizard. Enter the NBS Back Office through the Admin>NBS Back Office page.

**Comment by CPQcart** [comment]
Also when I exited as super user DNN was broke with 404 error

**Comment by leedavi** [comment]
Hi, OK the DB is correct, it's using XML fields so we only have a handful of tables.

But you should not be getting a 404 on exit of the BO.  Have you got an installation I can see?

Have you got any errors in the DNN event log?
