### ISSUE TITLE
Is this the correct forum to ask questions about how the store operates?

### ISSUE THREAD

**Issue by crwolverton** [nbrightproject/NBrightBuy#12]
I am a newbie to NB Store and GitHub.  I see most of the dialogue on this site is related to "issues" in which thing are not working correctly.  I have some questions that are not addressed in the online Manager Guide and was wondering if this is an appropriate forum to ask those questions.  These are general questions about the operations of the store and are probably not issued related to coding problems. For example I have store data from a previous store and would like to import that into NB Store but cannot determine the correct schema/format for the input file.  Also I am not getting anything in the "Details" view of the Product Viewer on the Details page and cannot determine why.  Thanks in advance.

**Comment by leedavi** [comment]
Hi,  With the move to GitHub, we've lost a central place for downloads and discussions.   I'm not sure what best to do about it at the moment, I've re-opened the discussions on the codeplex site, so there is probably the best place to post questions.

https://nbrightbuy.codeplex.com/discussions

But in answer to your questions, we do have migration program.  I've place the source on codeplex, unfortunately it's not fully tested yet and therefore we've not released it.

https://nbrightbuy.codeplex.com/releases/view/617060

With the product list, my guess is that you've either not applieds the correct page in the module or BO settings.  There is a list page and detail page in the BO, plus there is also a target module option in the product view module.

**Comment by crwolverton** [comment]
Thanks you very much for the quick response and information, I was able to correct the problem with the product list as you suggested.  I will give the migration a go this afternoon.  I will keep an eye on both codeplex and GitHub for more information but I was able to get a lot from your NB Store demo at http://nbs3.nevoweb.com/en-gb/.  Gave me a good reference on the BO and how the site should be setup.  One further thing I came across was, on two different occasions (yes I did this twice (: ) when I mistakenly set my home page to use the NBright BO skin.  The first time I has to reinstall dnn because I couldn't figure out what went wrong or to fix it..  The second time I was able to browse to a different page using the address bar and then use the Pages Manager to change the skin back.  Guess I will try to figure a way to prevent a client from making the same mistake, but now I know how to correct the problem.

**Comment by in8dna** [comment]
I appreciate your Q&A - thanks

**Comment by leedavi** [comment]
Hi,

No, the best place to ask question for now is https://nbrightbuy.codeplex.com/discussions

**Comment by in8dna** [comment]
David has finished a bit of a Migration Tool upgrade. It worked for us to move some 3400 products from v2 into v3. Others might ask about this as there are numerous benefits to upgrading into v3 that we appreciate, and made the effort worth our while.
