### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by seekthelight** [nbrightproject/NBrightBuy#13]
So I set up the NB Store v3 and added two products.
While testing and attempting to "buy" one of the products, an error occurs and the message is: "The given key was not present in the dictionary."

Do you know of anyway to fix such an error?

**Comment by seekthelight** [comment]
Oddly, overnight, the products duplicated themselves and one was working and was able to be added to the cart; however, the others were not and upon attempting to add them to the cart, the error message came back.

**Comment by leedavi** [comment]
Can you post question on codeplex for now, please, I'm trying to keep everything in one place.  But in answer to your question, I've never heard of products duplicating themselves and the error message is fairly generic,  has you got an installation where I can see this happening?  if so can you send me a link through codeplex private message, too leedavi.
