### ISSUE TITLE
Discounts do not pass to PayPal

### ISSUE THREAD

**Issue by seekthelight** [nbrightproject/NBrightBuy#14]
When allowing a discount in the cart, for an example, the total is $89 and you have a promotional $30 off, thereby making the total $59. When passed to PayPal then the original total without the discount is sent.

**Comment by leedavi** [comment]
Are you using v1.0.5 of NBrightBuyPayPal, This should have been fixed in that version.

**Comment by seekthelight** [comment]
I used the version located here: https://nbrightpaypal.codeplex.com/

**Comment by leedavi** [comment]
There are 2 versions there, v1.04 and v1.05.  make sure you have v1.0.5 installed.

**Comment by seekthelight** [comment]
The one I have is marked 1.0.5....

**Comment by leedavi** [comment]
OK, looks like the code base is correct, but the install package doesn't have the correct compiled version.  I've upload v1.0.6, try that.  Thx for pointing it out.

**Comment by seekthelight** [comment]
We updated the code and the issue is solved, however a new one is made. Now the shipping charges are not making it over to PayPal.

Sent from my Windows Phone

**Comment by leedavi** [comment]
Hi,
Sorry about the late reply, I've been crushed under workload.

Is this still a problem?  looking at the code, it seems to be passing the shipping attached to the order.  

Have you got a test system I can look at?  If so  PM or email me a link.

**Comment by seekthelight** [comment]
I'm sorry, I forgot to put that it was the mini cart. I took the mini cart off and everything is okay.

Sent from my Windows Phone
