### ISSUE TITLE
Can't figure out how to add second shipping option

### ISSUE THREAD

**Issue by mcastano24** [nbrightproject/NBrightBuy#149]
I can't seem to figure out how to add a second shipping option i.e express and flat rate shipping

**Comment by leedavi** [comment]
Go into Admin/Plugins, Edit the shipping plugin and change the "ref" field to "shipping2".  You should now have 2 shipping options,  (Both the same calculation, but you can change the settings)

**Comment by mcastano24** [comment]
Thanks for the help, I now have the two shipping options however I am unable to change the name. 





 

 

I have tried updating the Default Name however that only changes the name to one of them and leaves the other one showing “ Shipping “ which is no good

 

Thanks again

**Comment by mcastano24** [comment]
thank you!

**Comment by Tychodewaard** [comment]
FYI: A video on how to:
https://www.youtube.com/playlist?list=PLMcSsqN8KrgzmlKiUuLXIWduBRZuyjqC1
