### ISSUE TITLE
No Administration NBS Backoffice page

### ISSUE THREAD

**Issue by JAB33699** [nbrightproject/NBrightBuy#15]
Hi,
after installing the NBS Store I haven't got the NBS Backoffice page.
What can I do?
Regards Jürgen

**Comment by JAB33699** [comment]
Hi,
after installing the nbs-example-setup.template file I enter the NBS Backoffice. 
Now I cannot leave the backoffice with exit, I'm still in the backoffice.
Regards Jürgen

**Comment by leedavi** [comment]
Have a read of the "Entering Back Office" section of this page,

http://nbsdocs.nbrightproject.org/Documentation/Integratorguide/Installation.aspx

The BO is now a skin control, so you need to use the BO skin on the page.

As for not being able to exit, make sure you save the settings in the BO like it says in the above link.

**Comment by JAB33699** [comment]
Hi David,

I think I did that.

But:

The only think I can see ist he BO only, nothing more. No Pagelinks, no Admin Tags etc.

The Exit button doesn’t work.

Regards Jürgen

Von: David Lee [mailto:notifications@github.com] 
Gesendet: Mittwoch, 30. Dezember 2015 17:05
An: leedavi/NBrightBuy NBrightBuy@noreply.github.com
Cc: JAB33699 Juergen.Becker@CAD-Becker.de
Betreff: Re: [NBrightBuy] No Administration NBS Backoffice page (#15)

Have a read of the "Entering Back Office" section of this page,

http://nbsdocs.nbrightproject.org/Documentation/Integratorguide/Installation.aspx

The BO is now a skin control, so you need to use the BO skin on the page.

As for not being able to exit, make sure you save the settings in the BO like it says in the above link.

**Comment by leedavi** [comment]
So you see the BO, but no menu on the right?

can you send me a screen shot.

**Comment by JAB33699** [comment]
Hi,

I see the BO but nothing of my website.

As you can see there is nothing of my website and the exit button doesn’t work.

Before I forget: I wish you a happy new year.

Regards Jürgen

Von: David Lee [mailto:notifications@github.com] 
Gesendet: Donnerstag, 31. Dezember 2015 10:15
An: leedavi/NBrightBuy NBrightBuy@noreply.github.com
Cc: JAB33699 Juergen.Becker@CAD-Becker.de
Betreff: Re: [NBrightBuy] No Administration NBS Backoffice page (#15)

So you see the BO, but no menu on the right?

can you send me a screen shot.

**Comment by JAB33699** [comment]
Hi,

additional info:

Where must I define the theme?

I did it for the site theme. I think that is wrong.

Regards Jürgen

Von: David Lee [mailto:notifications@github.com] 
Gesendet: Donnerstag, 31. Dezember 2015 10:15
An: leedavi/NBrightBuy NBrightBuy@noreply.github.com
Cc: JAB33699 Juergen.Becker@CAD-Becker.de
Betreff: Re: [NBrightBuy] No Administration NBS Backoffice page (#15)

So you see the BO, but no menu on the right?

can you send me a screen shot.

**Comment by leedavi** [comment]
I can’t see the screen shots, but from what you describe it doesn’t sound like it’s installed correctly.  Ava first step do a reinstall of NBS and the go into the bo and see if you have the admin option in the menu on the right.  You need to into the bo admin settings and save before you do anything else in NBS.

**Comment by JAB33699** [comment]
HI,

Ok. My first problem is, that I doesn’t get the NBS BO in the admin tab of DNN not of NBS.

“Ava first step do a reinstall of NBS and the go into the bo” I cannot got into the BO because the NBS BO is missing in the DNN admin Tab.

Regards Jürgen

Von: David Lee [mailto:notifications@github.com] 
Gesendet: Donnerstag, 31. Dezember 2015 14:26
An: leedavi/NBrightBuy NBrightBuy@noreply.github.com
Cc: JAB33699 Juergen.Becker@CAD-Becker.de
Betreff: Re: [NBrightBuy] No Administration NBS Backoffice page (#15)

I can’t see the screen shots, but from what you describe it doesn’t sound like it’s installed correctly. Ava first step do a reinstall of NBS and the go into the bo and see if you have the admin option in the menu on the right. You need to into the bo admin settings and save before you do anything else in NBS.

**Comment by leedavi** [comment]
Ok, by saying the exit button doesn’t work, I assumed you had the Bo.

You need to create a page  in dnn and then set the skin of the of the page to the NBS Bo skin!  You should then be able to get into the Bo of NBS.

**Comment by JAB33699** [comment]
Hi,

OK. I understand. 

It is something strange that I don’t see the DNN Menüs in the NBS BO.

But the exit button works now and I’m on my website again.

Many thanks for your help.

And a happy new year.

Regards Jürgen

Von: David Lee [mailto:notifications@github.com] 
Gesendet: Donnerstag, 31. Dezember 2015 14:41
An: leedavi/NBrightBuy NBrightBuy@noreply.github.com
Cc: JAB33699 Juergen.Becker@CAD-Becker.de
Betreff: Re: [NBrightBuy] No Administration NBS Backoffice page (#15)

Ok, by saying the exit button doesn’t work, I assumed you had the Bo. 

You need to create a page in dnn and then set the skin of the of the page to the NBS Bo skin! You should then be able to get into the Bo of NBS.

**Comment by JAB33699** [comment]
Hi David,

do you have any German resources?

Or can I translate it and send you the result?

Regards Jürgen

Von: David Lee [mailto:notifications@github.com] 
Gesendet: Donnerstag, 31. Dezember 2015 14:41
An: leedavi/NBrightBuy NBrightBuy@noreply.github.com
Cc: JAB33699 Juergen.Becker@CAD-Becker.de
Betreff: Re: [NBrightBuy] No Administration NBS Backoffice page (#15)

Ok, by saying the exit button doesn’t work, I assumed you had the Bo. 

You need to create a page in dnn and then set the skin of the of the page to the NBS Bo skin! You should then be able to get into the Bo of NBS.

**Comment by leedavi** [comment]
Hi Jurgen,

We have no German resx at the moment, so if you want to translate it, that would be great!

Keeping in mind that v3.4 on GitHub is currently being tested and will be released soon, so if you can take the v3.4 branch resx that would be best, but anything you do will be gratefully received and included in the next release.

Regards,
Dave.
