### ISSUE TITLE
DNN 9 Support

### ISSUE THREAD

**Issue by maduranga001** [nbrightproject/NBrightBuy#153]
Hi,

Please, can you let me know if there is a DNN 9 supported NB module? I need to install this module and use on DNN 9.1.1 new website.

Thank you!

**Comment by leedavi** [comment]
The beta v3.6.7 should work.  

https://github.com/nbrightproject/NBrightBuy/tree/develop/Installation

**Comment by maduranga001** [comment]
Thank you for the reply. Is it good to use in a production site as it says it is on Beta4? Please, advise.

**Comment by leedavi** [comment]
It's behind the develop branch, it's usable but will NOT be the stable release.  Best to take develop branch.

**Comment by maduranga001** [comment]
When can we expect the stable DNN 9 version? Any idea or a plan?

Thank you!

**Comment by leedavi** [comment]
None of my clients have moved to DNN9, so I've only done basic test and usage on DNN9.  So I will release a stable release in Feb.  But it'll be tested against DNN8.  DNN9 should work, but I don't think DNN9 is ready for real life, yet.  Mainly I hate the new menu, it takes longer to do things, I'm unsure of the reason for the DNN9 release when it is so obviously behind DNN8 with the UI functionality.  When I feel DNN9 is ready I'll move all dev of NBS to DNN9, but at the moment it's still on DNN8.  But I've not found any showstoppers for running NBS on DNN9

**Comment by maduranga001** [comment]
Yes, correct. DNN 9 menus are a bit weird to use. But seems to be much faster than DNN 8.

For new DNN websites, we use the most recent stable DNN versions. This is why I use DNN 9 for the next DNN website. I need basic functions of the shop module like add and view products. No purchasing options.

NB store has all these features and feels it as a good free module as I am doing a low budget project. DNN 9 Compatibility is the only problem.

Thank you!

**Comment by maduranga001** [comment]
Hi,

I installed the module on DNN 9 and seems to be working fine. I just imported some products and categories from another NB store from another site.

I can see only 4 tables for the entire module in the database. Hope this is correct. Right?
But I can not find the categories on the database tables and do not know where it is stored. Also, how the products are finding the relevant category for each product? Please, can you advise me?

Actually, I am building another application and I need only the inventory part of the products.
So I need to combine with my other custom tables.

Thank you!

**Comment by leedavi** [comment]
Do a portal validation after import.  if your old store has not got the same lanaguges you'll have records missing.  Doing "Admin>Tools>Portal Validation" should fix it.

Here is an exmpalation of the table system: http://nbsdocs.nbrightproject.org/Documentation/Integrator-guide/Data-Format
