### ISSUE TITLE
Dashboard error

### ISSUE THREAD

**Issue by MartyNZ** [nbrightproject/NBrightBuy#154]
System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting date and/or time from character string. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() at System.Data.SqlClient.SqlDataReader.get_MetaData() at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) at System.Data.SqlClient.SqlCommand.ExecuteXmlReader() at Nevoweb.DNN.NBrightBuy.Components.SqlDataProvider.SqlDataProvider.GetSqlxml(String commandText) at Nevoweb.DNN.NBrightBuy.Admin.DashSummary.GetStats(Int32 portalId, Boolean forceRefresh) at Nevoweb.DNN.NBrightBuy.Admin.DashSummary.PageLoad() at Nevoweb.DNN.NBrightBuy.Admin.DashSummary.OnLoad(EventArgs e) ClientConnectionId:6177b19f-fdb7-4d19-b56d-9ad4879e7723 Error Number:241,State:1,Class:16

**Comment by leedavi** [comment]
A error like this has been reported before on product admin, but I can't recreate.
Have you got any issue with product admin?
Make sure you have the latest beta, 

here:  https://github.com/nbrightproject/NBrightBuy/tree/develop/Installation

**Comment by MartyNZ** [comment]
This was working fine when I first set the site up.
Every other aspect of the Back Office appears to be working, the issue just seems to be with the dashboard.
I have now upgraded the store to 3.6.5, no change.
Would you like to poke around the site? It's not a high traffic site so I have no problem having you look into it.

**Comment by leedavi** [comment]
First try and go into the Admin>Settings and do a save.  There was a change in settings, maybe this is a symptom of the changes,

**Comment by MartyNZ** [comment]
Yep. Tried it. No change.

**Comment by leedavi** [comment]
PM me a login and I'll take a look, if you want.

**Comment by MartyNZ** [comment]
You should’ve received an email

**Comment by leedavi** [comment]
Try running this on your DB.

exec NBrightBuy_DashboardStats 0

I tried on your version of the backup and it works on my server, does it work on yours?
I think, according to the error message, this is the SQl that is causaing the error.

**Comment by MartyNZ** [comment]
Hi David,
Error reported when I ran that command:
“Conversion failed when converting date and/or time from character string.”

**Comment by leedavi** [comment]
OK, What langauge and date format do you have in SQL server?  This looks like some kind of format that is not compatible??  not sure what, I know SQL can deal with formats differently, but I've never had a problem with it.

**Comment by MartyNZ** [comment]
[cid:image001.png@01D399B6.6D129BB0]

Cheers
Martyn

**Comment by leedavi** [comment]
hi Martyn, Not sure what you mean? Also,you shoudl reply on the thread, a reply email will post the email on the thread, with any sesitive data, for everyone to see.  (I've edit your comments to make it spam save.)

**Comment by MartyNZ** [comment]
Hi David,
If you're talking about the language etc. settings of SQL Server globally, I can't tell you that unless you can give me a script that pulls that information out. I can tell you I have 2 sites on the same server and this is the only one with the issue.

Hope that helps you help me. :-)

cheers
Martyn
