### ISSUE TITLE
ERROR - Razor Template Not Found: config. 

### ISSUE THREAD

**Issue by MartyNZ** [nbrightproject/NBrightBuy#156]
Error on payment page. Any idea where I start looking for this issue?

![capture](https://user-images.githubusercontent.com/13032309/35598221-e65bf100-0686-11e8-86eb-302385de3b35.PNG)

cheers
Martyn

**Comment by leedavi** [comment]
Have you got 3 payment gateway defined in the BO>plugins?

**Comment by MartyNZ** [comment]
Yes. PxPay Express, Paypal, and Manual. It seems to be the manual that's not working.

**Comment by leedavi** [comment]
Go into the BO and save the manual payment data.  I've seen this is hte settings are not saved.

**Comment by MartyNZ** [comment]
That sorted it.
Thanks

Cheers
Martyn
