### ISSUE TITLE
Option problem in ver. 3.6.5.1

### ISSUE THREAD

**Issue by BenderNETs** [nbrightproject/NBrightBuy#157]
Hello,
I'm trying to add some options to my articles. On the prodcut details page I see the dropdownbox with the options but they are all empty (I can see all empty options with values like "T5nU9bGZ" in the html code). Since I added options I can also not buy the article anymore. When I click on the buy button nothing happens.
All options are only "sizes" like "Small", "Medium", "Large" with no extra cost ($0).
Is there anything I missed or is this a bug?

Thanks,
Harald

**Comment by leedavi** [comment]
I take it you did put text in for the values.

Did you click the required checkbox?

I'm not aware of any issues with options and your the first to report this for v3.5, whcih has been out for quite a time now.

This is in French (Not had time to do the English, yet), but do a bing translate, see if it points something out.  But it's all fairly simple.

http://nbs3manager.nbrightproject.org/fr-fr/Documentation/Catalog/Articles-section/Options-of-products

Also post question on the forum, I'm trying to save GitHub for known issue.

https://forum.nbrightproject.org/

**Comment by BenderNETs** [comment]
I checked the required box. See attached. Are there any other settings I missed?

![screenshot_3](https://user-images.githubusercontent.com/17228217/36204492-7b07ad26-1159-11e8-91de-a7fbb92078d8.png)
![screenshot_2](https://user-images.githubusercontent.com/17228217/36204374-12b71518-1159-11e8-8e1d-bba471f1da7a.png)
![screenshot_1](https://user-images.githubusercontent.com/17228217/36204375-12c32196-1159-11e8-817a-0c433938de45.png)

**Comment by BenderNETs** [comment]
Just found out that the "Buy" button doesn't work on any article (even the ones without options). The only way I get them in the cart is by clicking the cart icon on the image in the product list.

**Comment by leedavi** [comment]
The add to basket is done via ajax, so check for any JS errors.  I can't remmeber what template is being used on v3.5.6, but I'll be surprised if this isn't working.

**Comment by leedavi** [comment]
Also make sure you have the mini basket on the page.  The JS for the ajax is included in that template.

**Comment by Tychodewaard** [comment]
The templates have been adjusted and there is a language parameter needed to show the options.

**Comment by Tychodewaard** [comment]
At one point the options where missing at my sites too.
First the options were missing in the back end. When adjusted the back end template (there was a path genxml/ which became later genxml/lang/genxml/ ) the options were back. 
The options were stored in the db with language parameters but then the front of the store became empty as the templates needed adjustment too. After adjusting the theme template, all was well

My ProductDisplayDetail.cshtml looks like this now:

@inherits NBrightBuy.render.NBrightBuyRazorTokens<NBrightRazor>
@using System.Linq
@using NBrightDNN
@using Nevoweb.DNN.NBrightBuy.Components;

@AddMetaData("resourcepath", "/DesktopModules/NBright/NBrightBuy/App_LocalResources/")


@{
    // assign Model, so we can resolve var in VS
    var product = (ProductData)Model.List.First();
    var info = (NBrightInfo)product.Info;
}

<div class="categorybreadcrumbs">@CategoryBreadCrumb(true, Model)</div>

<div class="nbs">

    <div class="productdetail" itemscope itemtype="https://schema.org/Product">

        @if (@product.Imgs.Count >= 1)
        {
            <div class="images">

                <div class="image">

                    <div class="addedtobasket atbshow@(info.ItemID)" style="display:none;">@ResourceKey("ProductView.addedtobasket")</div>

                    
                    @if (Model.GetSetting("enablefavorites") == "True")
                    {
                        <div class="favorite-flag">
                            <a class="wishlistadd" listname="nbsfavorites0" itemid="@(info.ItemID)">@ResourceKey("ProductView.wishlistaddicon-lg")</a>
                            <a class="wishlistremove" listname="nbsfavorites0" itemid="@(info.ItemID)" style="display: none;">@ResourceKey("ProductView.wishlistremoveicon-lg")</a>
                        </div>
                    }

                    @if (product.Imgs.Count > 0)
                    {
                        <a href="@(product.Imgs.First().GetXmlProperty("genxml/hidden/imageurl"))" data-imagelightbox="nbb"><img src="@ProductImage(info, Model.GetSetting("classicimagewidth"), Model.GetSetting("classicimageheight"))" alt="@(product.Imgs.First().GetXmlProperty("genxml/textbox/txtimagedesc"))" title="@(product.Imgs.First().GetXmlProperty("genxml/textbox/txtimagedesc"))" /></a>
                    }
                    else
                    {
                        <div class="noimage" style="height: @(Model.GetSetting("classicimageheight"))">
                            @(Model.GetSettingHtmlOf("noimageicon"))NO IMAGE
                        </div>
                    }
                    @if (@product.IsOnSale)
                    {
                        <div class="onsaleflag">@ResourceKey("ProductView.onsaleflag")</div>
                    }
                    @if (!@product.IsInStock)
                    {
                        <div class="outofstockflag">@ResourceKey("ProductView.outofstockflag")</div>
                    }
                    @if (product.HasProperty("promotionflag"))
                    {
                        <div class="promotionflag" @(ResourceKey("ProductView.promotionflag"))></div>
                    }
                </div>

                
                <ul class="gallery">
                    @{
                        var lp = 1;
                        foreach (var img in product.Imgs)
                        {
                            if (lp > 1)
                            {
                                <li class="image@(lp.ToString())">
                                    <a href="@(img.GetXmlProperty("genxml/hidden/imageurl"))" data-imagelightbox="nbb">
                                        <img src="/DesktopModules/NBright/NBrightBuy/NBrightThumb.ashx?src=@(img.GetXmlProperty("genxml/hidden/imageurl"))&amp;w=70&amp;h=0" alt="@(img.GetXmlProperty("genxml/textbox/txtimagedesc"))" title="">
                                    </a>
                                </li>
                            }
                            lp += 1;
                        }
                    }
                </ul>

            </div>
                        }

        
        <div class="purchasing entryid@(info.ItemID)">
            <input id="@(info.ItemID)_productid" type="hidden" value="@(info.ItemID)">
            <input id="lang" type="hidden" value="@(info.Lang)">

			<h1 itemprop="name">@(product.ProductName)</h1>
        

            <div class="price">
			@if (@info.GetXmlProperty("genxml/checkbox/callforprice").ToLower() == "true") {
				<div class="cfp">Prijs op aanvraag</div>

                

				
				} else {
					
					
					
					
					if (product.IsOnSale)
                {
                    <span>@ResourceKey("ProductView.onsale") : </span>
                    <span class="old"> @(NBrightBuyUtils.FormatToStoreCurrency(product.FromPrice()))</span>
                    <span class="sale"> @(NBrightBuyUtils.FormatToStoreCurrency(product.BestPrice()))</span>
                }
                else
                {
                    if (product.Models.Count > 1 || product.Options.Count >= 1 || product.FromPrice() > product.BestPrice()) // has models or options
                    {
                        <span>@ResourceKey("ProductView.from")</span>
                    }
                    <span> @(NBrightBuyUtils.FormatToStoreCurrency(product.BestPrice()))</span>
                }
					
					
					
					
					
				}
            </div>
			
			
			
			
			

                    <div class="bulkprice">

                
                        <div class="bulkpromo">
                            @foreach (NBrightInfo m in product.Models)
                            {
                                var unitcost = m.GetXmlPropertyDouble("genxml/textbox/txtunitcost");
                                var saleprice = m.GetXmlPropertyDouble("genxml/textbox/txtsaleprice");
                                var unitqty = m.GetXmlPropertyDouble("genxml/textbox/unitqty");
                                var orginalPrice = Math.Round(product.HighUnitPrice()*unitqty, 2);
                                var modelbestprice = unitcost;
                                if (saleprice > 0 && unitcost > saleprice)
                                {
                                    modelbestprice = saleprice;
                                }

                                if (unitqty > 1 & (orginalPrice != modelbestprice)) // display bulk and only if the bulk price is not the highest price.
                                {
                                    <div class="stamps">
                                        <div class="onsaleflag">-<span>@NBrightBuyUtils.CalcPricePercentageDiff(orginalPrice, modelbestprice).ToString("0")</span>%
                                        </div>
                                        <span class="old">@NBrightBuyUtils.FormatToStoreCurrency(orginalPrice)</span>
                                        <strong>@NBrightBuyUtils.FormatToStoreCurrency(modelbestprice)</strong>
                                    </div>
                                }
                            }
                        </div>


                    </div>
          
			
			
			
			

            @if (@info.GetXmlProperty("genxml/lang/genxml/textbox/txtsummary") != "")
            {
                <div itemprop="description" class="summary">@BreakOf(info, "genxml/lang/genxml/textbox/txtsummary")</div>
            }
			
			
			
			
			

			
			
			
			
			
			
			
			
			
			
			
			
			
			
            @if (@product.Models.Count >= 2)
            {
                var c = 0;
                <div class="models">
                    @if (Model.GetSetting("modeldisplaytype") == "0" && (product.Models.Count >= 2))
                    {
                        @ModelsRadio(info)
                    }
                    @if (Model.GetSetting("modeldisplaytype") == "1" && (product.Models.Count >= 2))
                    {
                        @ModelsDropDown(info)
                    }
                    @if (Model.GetSetting("modeldisplaytype") == "2")
                    {
                        foreach (NBrightInfo x in product.Models)
                        {
                            <div class="quantityoptions">
                                <a class="qtyminus" index="@(c)" href="javascript:void(0)">-</a>
                                <input type="text" id="selectedmodelqty@(c)" update="save" class="quantity" style='width: 21px' value="1" />
                                
                                <input id="selectedmodelid@(c)" type="hidden" value="@(x.GetXmlProperty("genxml/hidden/modelid"))">
                                <a class="qtyplus" index="@(c)" href="javascript:void(0)">+</a>
                                <label>@NBrightBuyUtils.GetItemDisplay(x, "{name} ({bestprice})", true) </label>
                            </div>
                            c += 1;
                        }
                    }
                </div>
                <div class="clearfix"></div>
            }

            @if (@product.Options.Count >= 1)
            {
                <div class="options">
                    
                    @ProductOptions(product)

                </div>
                <div class="clearfix"></div>
            }

            @if (product.ClientFileUpload)
            {
                <div class="options">

                    <div id="clientfileuploadmsg">
                        @ResourceKey("ProductView.clientfileuploadmsg")
                    </div>
                    <div id="clientfileuploadmsgend" style="display: none;">
                        @ResourceKey("ProductView.clientfileuploadmsgend")
                    </div>

                    <div class="fileUpload dnnSecondaryAction">
                        <span>@ResourceKey("OrderAdmin.choosefile")</span>
                        <input id='optionfile' update='save' class="normalFileUpload form-control" type='file' name="files[]" multiple />
                    </div>
                    <div id="progressbar" style="display: none;">
                        <div id="progressbarpercent"></div>
                    </div>

                    <input id='optionfilelist' style='display: none;' update='save' type='text' />
                    <input id='optionfileprefix' update='save' type='hidden' />

                </div>
                <div class="clearfix"></div>
            }



@if (@info.GetXmlProperty("genxml/checkbox/callforprice").ToLower() != "true") { 
                    if (Model.GetSetting("cataloguemode") != "True")
                    {
                        <div class="buy">
                            @if (@product.IsInStock)
                            {
                                if (Model.GetSetting("modeldisplaytype") != "2")
                                {
                                    <div class="quantityoptions">
                                        <a class="qtyminus" href="javascript:void(0)">-</a>
                                        
                                        @TextBox(info, "genxml/textbox/selectedaddqty", "class='quantity selectedaddqty' style='width:21px'", "1")
                                        <a class="qtyplus" href="javascript:void(0)">+</a>
                                    </div>
                                }
                                
                                <a class="addtobasket classicbutton" itemid="@(info.ItemID)" href="javascript:void(0)">@ResourceKey("ProductView.addtobasket")</a>
                            }
                            else
                            {
                                <span class="outofstock">@ResourceKey("ProductView.outofstock")</span>
                            }

                            <span class="return"><a href="@EntryReturnUrl(Model)" class="secondarybutton">@ResourceKey("ProductView.return")</a></span>

                        </div>
                    }
					
					
					
					
					} 
                    <div>
                        @HtmlOf(product.Info, "genxml/lang/genxml/hidden/promodesc")
                    </div>
                </div>
        <div class="clearfix"></div>

    
        @{
            var modeltableclass = "tab-content tab-hide";
        }
            <div class="details">

               <ul class="nav-tabs">
@if (info.GetXmlProperty("genxml/lang/genxml/edt/description") != "")
{
<li class="tab-active"><a href="#tab-1">@ResourceKey("ProductView.description")</a></li>
}
@*@if (product.Models.Count > 1) // has models
{
if (info.GetXmlProperty("genxml/lang/genxml/edt/description") == "")
{
modeltableclass = "tab-content tab-active";
<li class="tab-active"><a href="#tab-2">@ResourceKey("ProductView.models")</a></li>
}
else
{
<li><a href="#tab-2">@ResourceKey("ProductView.models")</a></li>
}
}*@
@if (product.Docs.Count >= 1)
{
<li><a href="#tab-3">@ResourceKey("ProductView.documentation")</a></li>
}
</ul>

                @if (Model.GetSetting("addthispubid") != "")
                {
                    <div class="sharingwidget"><div class="share">@ResourceKey("ProductView.share") :</div><div class="addthis_sharing_toolbox"></div></div>
                }

            @if (@info.GetXmlProperty("genxml/lang/genxml/edt/description") != "")
            {
                <div id="tab-1" class="tab-content tab-active">
                    <h3>@ResourceKey("ProductView.description")</h3>
                    @HtmlOf(info, "genxml/lang/genxml/edt/description")
                </div>
            }
            @if (@product.Models.Count > 1) // has models
            {


                <div id="tab-2" class="@(modeltableclass)">
                    <h3>@ResourceKey("ProductView.models")</h3>
                    <div class="models">
                        <table>
                            <tbody>
                                
                                @foreach (var m in product.Models)
                                {
					if (!bool.Parse(m.GetXmlProperty("genxml/checkbox/chkishidden")))
                                	{
					    <tr>
						<td class="models-option">@m.GetXmlProperty("genxml/lang/genxml/textbox/txtmodelname")</td>
						<td class="models-value">@m.GetXmlProperty("genxml/lang/genxml/textbox/txtextra")</td>
						@if (Model.GetSetting("productcode") == "True")
						{
						    if (m.GetXmlProperty("genxml/textbox/txtmodelref") == "")
						    {
							<td>NC</td>
						    }
						    else
						    {
							<td>@m.GetXmlProperty("genxml/textbox/txtmodelref")</td>
						    }
						}
						<td>
						    @if (product.BestPrice() < product.FromPrice())
						    {
							<span class="old">@NBrightBuyUtils.FormatToStoreCurrency(product.FromPrice())</span>
							<strong>@NBrightBuyUtils.FormatToStoreCurrency(product.BestPrice())</strong>
						    }
						    else
						    {
							<span>@NBrightBuyUtils.FormatToStoreCurrency(product.BestPrice())</span>
						    }
						</td>

						<td>
						    @if (!product.IsInStock)
						    {
							<strong>@ResourceKey("ProductView.outofstock")</strong>
						    }
						</td>
					    </tr>
					}
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            }
            @if (@product.Docs.Count >= 1)
            {
                <div id="tab-3" class="tab-content tab-hide">
                    <h3>@ResourceKey("ProductView.documentation")</h3>
                    <ul class="documents">
                        
                        @foreach (var doc in product.Docs)
                        {
                            <li>
                                <i class='fa fa-file-text fa-2x'>@ResourceKey("ProductView.filebullets")</i><span class="documentname">@doc.GetXmlProperty("genxml/textbox/txttitle")</span><span class="documentdescription">@doc.GetXmlProperty("genxml/textbox/txtdocdesc")</span>
                                <a class="documentlink classicbutton" href='/DesktopModules/NBright/NBrightBuy/XmlConnector.ashx?cmd=docdownload&downloadname=@doc.GetXmlProperty("genxml/textbox/txtfilename")&filename=@doc.GetXmlProperty("genxml/hidden/filerelpath")'>@ResourceKey("ProductView.download")</a>
                            </li>
                        }
                    </ul>
                </div>
            }

        </div>
        
        
        @if (@product.GetRelatedProducts().Count >= 1)
        {
            <h3>@ResourceKey("ProductView.recommend")</h3>
            <div id="relatedwrapper" class="productlist">
                
                @foreach (var rp in product.GetRelatedProducts())
                {
                    var rproduct = new ProductData(rp.ItemID, rp.Lang);
                    <div class="product" style="width: @Model.GetSetting("relateditemwidth")px; height: @Model.GetSetting("relateditemheight"); margin-bottom: @Model.GetSetting("relateditembottommargin")px">

                        <div class="productimg" style="width: 294px; height: @(Model.GetSetting("relateditemimagecontainerheight"))">

                            @if (rp.GetXmlProperty("genxml/imgs/genxml[1]/hidden/imageurl") != "")
                            {
                                <div class="image" style="height: @(Model.GetSetting("relateditemimagecontainerheight"))">
                                    <img title="@(info.GetXmlProperty("genxml/lang/genxml/textbox/txtsummary"))" src="@ProductImage(rp, Model.GetSetting("relatedimagewidth"), Model.GetSetting("relatedimageheight"))">
                                </div>
                            }
                            else
                            {
                                <div class="noimage" style="height: @(Model.GetSetting("relateditemimagecontainerheight"))">
                                    @(Model.GetSettingHtmlOf("noimageicon"))
                                </div>
                            }
                        </div>

                        <div class="description">
                            <h2><a href="@EntryUrl(rp, Model)">@ProductName(rp)</a></h2>

                            @*<div class="price">

                                @if (product.IsOnSale)
                                {
                                    if (product.Models.Count > 1)
                                    {<span class="from">@ResourceKey("ProductView.from")</span>}<span class="old">@(NBrightBuyUtils.FormatToStoreCurrency(rproduct.FromPrice()))</span><span class="sale">@(NBrightBuyUtils.FormatToStoreCurrency(rproduct.SalePrice()))</span>
                                }
                                else
                                {
                                    if (product.Models.Count > 1) // has models or options
                                    {<span class="from">@ResourceKey("ProductView.from")</span>}@(NBrightBuyUtils.FormatToStoreCurrency(rproduct.FromPrice()))

                                }

                            </div>

                            @if (rproduct.IsOnSale)
                            {
                                <div class="onsaleflag">@ResourceKey("ProductView.onsaleflag")</div>
                            }

                            @if (!rproduct.IsInStock)
                            {
                                <div class="outofstockflag">@ResourceKey("ProductView.outofstockflag")</div>
                            }

                            <a href="@EntryUrl(rp, Model)" class="classicbutton entryurl">@ResourceKey("ProductView.view")</a>*@

                        </div>

                    </div>
                }
            </div>
        }

    </div>

</div>

**Comment by BenderNETs** [comment]
The missing mini basket module on the product details page helped to get the "Buy" button to work. I'm still struggling with the options on the same page. They still don't show up. Are there really any changes I have to make in the template file to get the options to show up? The options show up in the BackOffice as shown in the screenshot.

**Comment by BenderNETs** [comment]
I got it to work updating the templates. Thanks all...
