### ISSUE TITLE
New Product Custom Field and Display on the Product list View

### ISSUE THREAD

**Issue by maduranga001** [nbrightproject/NBrightBuy#158]
I was trying to add a custom field for the product and also view it in the product list view. But It is not working for me. Please, can you advise me how to do this exactly?

My Custom field name should be "Maga Points" it should be a textbox to add only decimals.
(0.1-250 range only.)

How can I do this? Can I do this without doing any source module compilation and with only doing source change thorough FTP?
I am using NBS_3.6.7_Install version.

Please, help.
Thank You!

**Comment by leedavi** [comment]
http://www.nbrightproject.org/Documentation/Developer-guide/Custom-Fields

https://forum.nbrightproject.org/
