### ISSUE TITLE
i can't see nb-template in site wizard local install

### ISSUE THREAD

**Issue by maysam7026** [nbrightproject/NBrightBuy#16]
hi 
i installed
1 latest nb-sys 
2 latest nb-package 
and the copy nbs-example-setup.template to _defualt folder and run site wizard from admin menu but in select skin page i can't see nb template!
 please help me
thankyou

**Comment by FabioParigi** [comment]
@maysam7026 
not so clear can you explain better your problem, please make one snapshot
Fabio
