### ISSUE TITLE
Cant find Paging Template for ProductDisplayList

### ISSUE THREAD

**Issue by inu-web** [nbrightproject/NBrightBuy#160]
Hi!
Maybe I am searching in the wrong place - I cannot find the part of the theme/template where to change the (cs)html markup of the paging control in the ProductDisplayList

Can anybody please give me a hint where to find this part?
Thanks in advance, any help is highly appreciated.
regards
Gerald

**Comment by leedavi** [comment]
Depends whcih version you use.  But the latest is: NBS_AjaxProductDisplayList_paging

https://github.com/nbrightproject/NBrightBuy/tree/develop/Installation

Ask questions here please: https://forum.nbrightproject.org/

**Comment by inu-web** [comment]
Thanks Dave - using NBrightBuy v3.5.11. 
sorry ...  I wasnt aware of the new forum - Ill post future topics there
thanks
Gerald

**Comment by leedavi** [comment]
Sorry, but in v3.5 it was hardcoed in code.

            CtrlPaging.HrefLinkTemplate = "[<tag type='valueof' databind='PreText' />][<tag type='if' databind='Text' testvalue='' display='{OFF}' />][<tag type='hrefpagelink' moduleid='" + ModuleId.ToString("") + "' />][<tag type='endif' />][<tag type='valueof' databind='PostText' />]";


Not much you can do unless you upgrade or play with css.

**Comment by inu-web** [comment]
Thanks for clearing that out - I will try to just move it into my template with jquery - better than nothing ;-)
