### ISSUE TITLE
How to show all items

### ISSUE THREAD

**Issue by ufoloko** [nbrightproject/NBrightBuy#163]
I have a page with products page, but by default i want to show all catalog. Now is needed to chose a category to show that category, how i can show by default all items ?

**Comment by Tychodewaard** [comment]
I always create the first category at shop level. That way you can select
the category in the settings of the module of the list page.

Does that work for you?

Op wo 11 jul. 2018 om 18:59 schreef ufoloko <notifications@github.com>

**Comment by leedavi** [comment]
try what Tycho said, but don't forget to turn on cascade in the module settings.
