### ISSUE TITLE
Upgrading from NBStore

### ISSUE THREAD

**Issue by micahsdad1402** [nbrightproject/NBrightBuy#17]
I'm currently using the old NBStore.

Is there an upgrade path, or do I have to start again?

Is the Direct Payment Solutions Payment Gateway supported with the new product? This wasn't on the list

**Comment by thienvc** [comment]
Me too, waiting for upgrade path and keep all data from old of this.

**Comment by leedavi** [comment]
There is only a migration path for NBSv2 to NBSv3.  The codebase is so different an upgrade was not really possible.

You'll need to build a new site and then use the migration program to move your data.

https://github.com/FabioParigi/NBrightBuyMigrate

**Comment by micahsdad1402** [comment]
The other part of the question was related to support for Direct Payment Solutions.

**Comment by leedavi** [comment]
No the only ones we have so far are listed here..

http://nbsdocs.nbrightproject.org/Documentation/Downloads.aspx

There is a VS template to help create gateways and some basic instructions here..

http://nbsdocs.nbrightproject.org/Documentation/Developerguide/PaymentGateway.aspx
