### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by dvdobrovolskiy** [nbrightproject/NBrightBuy#19]
Still having troubles with categories edit.
1. Press add several times to have amount of fields to fill in. Fill them in and decide you need more. Press add button and loose all data you already filled in.
2. Do it again - press "add" many times (remember not to press add before save this time) but just double click on fields where mozilla already remember you previous text for field (so you just double click on field and choose value). Press save and loose all predefined fields (store saves only fields that was modified my keyboard - not by double click and select)

**Comment by leedavi** [comment]
Um!!  Yes, it uses a flag when the field is altered to tell it to update, this is to save us updating everything on every save.  Mouse clicks are not in the JS to trigger the flag.

I'll make a note to try and add this.

**Comment by micahsdad1402** [comment]
I've just downloaded the latest version of 3.5, and am having this issue. I can't get very far without categories so it seems.

I add the category. It says it's updated. I add the article to the category, and says it's updated, then when I try and look at the article, it's not associated with a category. I go back and look at the categories, and there is none there.

Do we have an ETA on this?

**Comment by micahsdad1402** [comment]
Just noticed that when I look at one category dropdown it shows my cateogry 3 times, but it's not showing up in BO Categories.

**Comment by micahsdad1402** [comment]
When I create a new category, it then is OK until I look at the articles.

When I go back it's missing.

However then appears as a property.

**Comment by BryanNZ** [comment]
@micahsdad1402 I had similar issues with categories and also saving images previously and what seemed to work was moving from a http://mydomain.com/sitename to a http://sitename.mydomain.com site alias. not sure if this is relevant to your situation but thought I would share.

**Comment by dvdobrovolskiy** [comment]
Problem still exists and it is annoing

**Comment by leedavi** [comment]
Hi,
We're mixing different problems here.

Dima, sorry I'll try and find time to alter the JS to pickup a mouse click.

John, I just tried but I can't recreate your problem.  Can you give me simple steps to recreate or PM me a link and login to see this happening on your install?  Because Categories and Properties are the same apart from a flag on the record I can understand how this might happen, but I need to recreate it.  

Also make sure you have the latest NBrightDNN_TemplateSys installed.

http://nbsdocs.nbrightproject.org/Documentation/Downloads.aspx

**Comment by dvdobrovolskiy** [comment]
many tnks
I did update NBrightDNN_TemplateSys

making test website based an 3.5 good job! a lot of impruvements

**Comment by micahsdad1402** [comment]
For another reason I did a clean install of my test site, and started with 3.5 and that's all working fine. However I did have to manually create the image, docs & uploads folder under nbstore in the portal. This was there in the previous one so not sure what that's about.

**Comment by leedavi** [comment]
The folders not being created is odd, it  should create then when you save the store setting. Other people have mentioned this, but I've never know it fail for me!

My only guess is that on some OS the base folder needs to be created before the actual upload folders, I'll add that code and see if this solves it.
