### ISSUE TITLE
Importing Products 

### ISSUE THREAD

**Issue by micahsdad1402** [nbrightproject/NBrightBuy#20]
I'm trying to use the import feature.
First thing I tried was to import using the xml format from nbstore v2. 
When I do that the page flashes, the filename disappears, and then nothing happens. No messages and nothing imported.
So next step was I created a product and attempted to export it so I can see the XML file, and it just throws an error (in the url) that it can't find a file path.
http://localhost/Default.aspx?tabid=3224&error=Could+not+find+a+part+of+the+path+%27C%3a%5cinetpub%5cwwwroot%5cgoldrushtechnology%5cPortals%5c2%5cNBStore%5cuploads%5cexport.xml%27.&content=0

I can't find any documentation on this either.

**Comment by leedavi** [comment]
Hi John,

I know there's an issue with the import message, addly it'll show if you then go back into the admin>setting.  (it's on the todo list)

As for the export failing, have you made sure the app pool file permissions are correct?  I use this function to move products between my dev systems and never noticed an issue!

Also, have you made sure your not running in a child portal.

Sorry about the documentation, I know it's poor, but things like earning a living keep getting in the way.  I'm going to try and improve it for the next version release.
