### ISSUE TITLE
Uploading Images

### ISSUE THREAD

**Issue by micahsdad1402** [nbrightproject/NBrightBuy#21]
Just tried to upload an image.
It goes through the process, and then no image appears. Just the icon showing that there is no image.
I then delete the image
If I try and add the image, all the images I deleted (except they aren't there) reappear. So I now have 4 images, but nothing in them.

**Comment by leedavi** [comment]
The image not displaying could be linked to the problems you have with export and import, maybe file permissions or child portal.

As for the images reappearing, this is a side effect of the undo option, the images are only moved to a hidden div until the save (to allow Undo option).  Adding an image has the effect of moving then back, I need to put a save before the add.

Also, can you please post question on codplex, I'm trying to only have 1 source and I'm using that for now.

http://nbrightbuy.codeplex.com/discussions

**Comment by micahsdad1402** [comment]
OK. It's just that you go to codeplex, and it says you've moved to Github... all a bit confusing.

I think I have some permissions errors. I'm also getting issues with All Users on the Page Permissions such that if I select View Page, Edit Page also is selected etc. I have a recollection that this is related to file permissions. The app pool uses the Network Service, and it has read, write modify

I just changed the app pool and it solved the issue with the images, and the export.
still have the issue with the page permissions though!

**Comment by Scippy** [comment]
I had a similar problem, but it was caused by lack of the images folder. The solution was to create the folder manually.

**Comment by micahsdad1402** [comment]
Thanks. Creating the folder solved the issue.
