### ISSUE TITLE
Classic theme has hardcoded image width 

### ISSUE THREAD

**Issue by MikeeUK** [nbrightproject/NBrightBuy#24]
Hi, The classic theme "NBright\NBrightBuy\Themes\Classic\Default\List.htm" has a hard coded value for productimg of 294px, setting it to width:[Settings:classicitemwidth]px allows the image and the overlay to resize but alas not the the required size.

**Comment by leedavi** [comment]
That setting token should be changable from the module settings?  I'm not sure why the designer put a hardcoded value in there, but all this templates will be changed for the next release.  You can also create the theme at portal level and alter that value if you wish and it will override the module level template.
