### ISSUE TITLE
PayPal - incorrectly formatted item amount

### ISSUE THREAD

**Issue by VinaiK** [nbrightproject/NBrightBuy#26]
Haribol!
When I click the checkout button and expect to be taken to the Paypal page, i get the error:

> The link you have used to enter the PayPal system contains an incorrectly formatted item amount.

I´m using EUR as currency code. 
You can see it in [http://loja.bibliopolis.info/Loja-Online](http://loja.bibliopolis.info/Loja-Online)

Any help would be much appreciated,

Thanks

**Comment by leedavi** [comment]
In the paypal settings there is a debug mode.  Put it into debug made and you shoudl get a file on the portal root called.

debug_NBrightPayPalpost.html

Give the payment a go in debug mode and lets see what's in that file.

**Comment by VinaiK** [comment]
Hi! Thank you for the quick reply!

I did as you adivised but the file debug_NBrightPayPalpost.html was not created...The debug files i can see on portal root are:

debug_menu.html
debug_treemenu.html
debug_addressadd.xml
debug_addtobasket.xml
debug_convertedcart.xml
debug_currentcart.xml
debug_entry.xml

I can give you admin credentials to the portal so that you can have a closer look if you want/need?

Thank you !

**Comment by VinaiK** [comment]
Hello David,

i realized that the issue with paypal payment is somehow related to portal
default language. If it is set  to English (United States) everthing works
fine, but not when it is set to portuguese for example.

2016-05-07 7:05 GMT+01:00 David Lee notifications@github.com:

**Comment by leedavi** [comment]
OK, there was a issue with an early verison on currency display.

Make sure you have the latest released verison of:

Template system  (I've just upload v3.4.0)
NBSv3
paypal provider

http://nbsdocs.nbrightproject.org/Documentation/Downloads.aspx

**Comment by VinaiK** [comment]
I have installed TemplateSys_v03.04.00 but unfortunately the issue was not
solved...

2016-05-18 17:58 GMT+01:00 David Lee notifications@github.com:

**Comment by Scippy** [comment]
I had the same problem but I have solved!
I've installed 1.0.7 version downloaded from NBrightPayPalPaymentProvider
First of all I note that the source code it is missing wherever!
To fix this problem I had to edit the NBrightPayPalPaymentProvider.dll with Reflector.
I explain the issue and solution:
I'm testing with DNN8.0.3 and TemplateSys_v08.00.00.06 with NBrightStore 3.5.0.35 on IT locale and EUR currency.
When I checkout with Paypal the sandbox inform me that the amount value is not in correct format. To fix it I've changed in Public Sub LoadSettings(ByVal oInfo As OrderData)
all conversions of ShippingAmount, TaxAmount, Amount.**tostring("0.00")** into **.tostring("0,00")**
After this change it work fine!
I'm sorry, it is a long time to fix this little problem but pending a official solution by Leedavi, to temporary fix you can download my recompiled dll from this url: [NBrightPayPalPaymentProvider.dll](http://95.110.209.182/Codepoint/Files/NBrightPayPalPaymentProvider.dll)

**Comment by leedavi** [comment]
Hi, 
Sorry I've missed the fact this issue was not solved.

the code can be found on github.

https://github.com/leedavi/NBrightPayPal

The format of "0,00" will work for you in it-IT, but it'll fail in English.  I'll have a look and see if I can work out a more permanent solution.

**Comment by leedavi** [comment]
Hi Scippy,

I've done some tests with the latest version of the paypal provider using "0.00" format and everything looks OK.

English data passed to paypal:

```
        <input type="hidden" name="currency_code" value="EUR" />
        <input type="hidden" name="cancel_return" value="http://nbs3.test.com/en-us/Payment/orderid/76/status/0" />
        <input type="hidden" name="notify_url" value="http://nbs3.test.com/DesktopModules/NBright/NBrightPayPal/notify.ashx" />
        <input type="hidden" name="custom" value="en-US" />
        <input type="hidden" name="business" value="" />
        <input type="hidden" name="item_name" value="16080476" />
        <input type="hidden" name="amount" value="20.00" />
        <input type="hidden" name="shipping" value="0.00" />
        <input type="hidden" name="tax" value="0.00" />
        <input type="hidden" name="lc" value="US" />
```

French data passed to paypal: 

```
        <input type="hidden" name="currency_code" value="EUR" />
        <input type="hidden" name="cancel_return" value="http://nbs3.test.com/fr-fr/Payment/orderid/78/status/0" />
        <input type="hidden" name="notify_url" value="http://nbs3.test.com/DesktopModules/NBright/NBrightPayPal/notify.ashx" />
        <input type="hidden" name="custom" value="fr-FR" />
        <input type="hidden" name="business" value="" />
        <input type="hidden" name="item_name" value="16080478" />
        <input type="hidden" name="amount" value="20,00" />
        <input type="hidden" name="shipping" value="0,00" />
        <input type="hidden" name="tax" value="0,00" />
        <input type="hidden" name="lc" value="FR" />
```

In fact when I use "0,00" for the ToString("0,00") I find  the number format wrong??

I wonder is this is to do with the language of the hosting server, are you running your server in Italian?

**Comment by Scippy** [comment]
Hi Leedavi,
you are right! I've downloaded source code version and debug it and now I'm able to understand the real problem!
What I thought was wrong, Paypal always want the formatting of currency with "." separator, then the issue with FR and IT is just that you pass it with "," decimal separator. I've fix the problem on PayData.cs in this way:
`
using System.Globalization;

Amount = (appliedtotal - alreadypaid).ToString("0.00", CultureInfo.InvariantCulture);
ShippingAmount = oInfo.PurchaseInfo.GetXmlPropertyDouble("genxml/shippingcost").ToString("0.00", CultureInfo.InvariantCulture);
TaxAmount = oInfo.PurchaseInfo.GetXmlPropertyDouble("genxml/taxcost").ToString("0.00", CultureInfo.InvariantCulture);
`

**Comment by leedavi** [comment]
OK, Thanks.  I'll update the source and re-release.
