### ISSUE TITLE
Microsoft Azure SQL DB Deploy error

### ISSUE THREAD

**Issue by CTGControls** [nbrightproject/NBrightBuy#27]
The table NBrightBuyIdx doesn't have a primary key. I set the column ItemId to the tables primary key. After doing so I was able to deploy
### When trying to deploy to Azure I got this error:

One or more unsupported elements were found in the schema used as part of a data package.
Error SQL71564: Table Table: [dbo].[NBrightBuyIdx] does not have a clustered index.  Clustered indexes are required for inserting data in this version of SQL Server.
 (Microsoft.SqlServer.Dac)

**Comment by leedavi** [comment]
OK thx, I didn't realize Azure forced primary key.  I'll make a note to fix it. I suggest you try and make the primary key unique by adding the "Lang" field to make a composite key of ItemId + Lang.

The NBrightBuyIdx table is only for speeding up search by making a SQL index from the table., I'm unsure what effect adding a primary key might have, but my guess is that it should be OK.
