### ISSUE TITLE
Uploading Transparent PNG images

### ISSUE THREAD

**Issue by maduranga001** [nbrightproject/NBrightBuy#28]
Hi,

I uploaded transparent background PNG images and all are coming with a black background on the product details page for the main product picture. Please, can you advise, if we can not upload transparent PNG images for the product images?

What can I do for this? Please, can you advise?

Thank You!

**Comment by micahsdad1402** [comment]
This was in issue with the old NBStore, so I guess it's still here. I suspect it's related to the thumbnail generation etc. I've always used jpg.

**Comment by leedavi** [comment]
Yes, this is a known issue with the resizer code. jpg is the best option.
