### ISSUE TITLE
Customisations required.

### ISSUE THREAD

**Issue by MartyNZ** [nbrightproject/NBrightBuy#3]
Is it possible to set this store up as follows:
1. Client sells vintage audio equipment all over the world. Has a price for each product but sets the shipping cost once someone shows an interest in a product. Therefore would like to show a simple product catalogue (4 categories) with just an image, product name, brief description and price. And then a button that offers 'request quote for shipping' or similar.
2. Each item is a one off but it is VERY important that products remain visible even after purchase as he gets many visitors to the site just looking for spec's etc. on a listed item. Therefore we would like to be able to mark an item as 'sold' so that it remains in the list but drops to the bottom.

Is this possible and if so, how do I do it. I'm finding your documentation confusing and inconsistent with the what I see on the screen.

I'm sure this is all just growing pains and I look forward to getting my head around the new system. It shows great promise.

cheers
MartyNZ

**Comment by robaxx** [comment]
We added a ton of different product statuses precisely for purposes such as this, but off the top of my head I can't recall what they are and I haven't got a copy with me. The statuses are on the models.  Try them one after the other and see what happens. I recall I think 3-4 of them are statuses that have an effect on the product and the rest are just for record purposes. For the request quote function, just run the buyer through the checkout without a payment. There's no facility to place an order on hold and then let the buyer pay for it later.

**Comment by MartyNZ** [comment]
![capture](https://cloud.githubusercontent.com/assets/13032309/8514305/58da85c0-23e0-11e5-8154-c9cd7b7bcb84.PNG)
Sorry Rob, but I'm not seeing anything other than the usual status's. Am I looking in the wrong place?

**Comment by MartyNZ** [comment]
HI Again Rob,
Ok, I think I've figured out what you were talking about. I've created a new property called 'Property Status' and given it two settings, 'For Sale' & 'Sold' I've then set 'For Sale' as the default property in the Product View.

Am I right in thinking this will filter all products to display only those 'For Sale'? If so I can probably work with that, although my brief is to be able to sort, 'For Sale' items first and then 'Sold' items. Is this possible?

**Comment by MartyNZ** [comment]
Update. I've now found what you're talking. You have to 'Activate Stock' to see the status dropdown list. But I cannot see a way to add options to this list, and then how do I filter or sort on it?

I would prefer to not have to activate stock. It's just one more step my non-geek client has to remember.
