### ISSUE TITLE
Creating a new theme

### ISSUE THREAD

**Issue by micahsdad1402** [nbrightproject/NBrightBuy#30]
Dave,

I need to create a new theme.

I copied the ClassicRazor theme, edited it replacing ClassicRazor with GRT.Razor 

However I'm getting this error:

`System.InvalidOperationException: The same key was already used for another template! at RazorEngine.Templating.DelegateTemplateManager.<>c__DisplayClass5_0.b__0(ITemplateKey k, ITemplateSource oldSource) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, TValue addValue, Func`3 updateValueFactory) at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String templateSource, String name, Type modelType, Object model, DynamicViewBag viewBag) at Nevoweb.DNN.NBrightBuy.Components.NBrightBuyUtils.RazorRender(Object info, String razorTempl, String templateKey, Boolean debugMode)System.InvalidOperationException: The same key was already used for another template! at RazorEngine.Templating.DelegateTemplateManager.<>c__DisplayClass5_0.b__0(ITemplateKey k, ITemplateSource oldSource) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, TValue addValue, Func`3 updateValueFactory) at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String templateSource, String name, Type modelType, Object model, DynamicViewBag viewBag) at Nevoweb.DNN.NBrightBuy.Components.NBrightBuyUtils.RazorRender(Object info, String razorTempl, String templateKey, Boolean debugMode)System.InvalidOperationException: The same key was already used for another template! at RazorEngine.Templating.DelegateTemplateManager.<>c__DisplayClass5_0.b__0(ITemplateKey k, ITemplateSource oldSource) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, TValue addValue, Func`3 updateValueFactory) at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String templateSource, String name, Type modelType, Object model, DynamicViewBag viewBag) at Nevoweb.DNN.NBrightBuy.Components.NBrightBuyUtils.RazorRender(Object info, String razorTempl, String templateKey, Boolean debugMode)`

Someone also reported this on codeplex.

I guess there is a template key defined somewhere, but I can't find it!

Help much appreciated.

**Comment by micahsdad1402** [comment]
It seemed to solve itself. I think it was a cache issue after I renamed stuff in the theme.

I now have another issue with basket not refreshing. I'll investigate more and if I don't find it I'll raise another issue.

**Comment by leedavi** [comment]
The Razor Engine caches the compiled template.  You need to restart the app pool to clear it.  You can also put NBS into debug mode when developing.  But be careful to turn debug off for production it causes a memory leak in Razor Engine.
