### ISSUE TITLE
Basket Not Updating

### ISSUE THREAD

**Issue by micahsdad1402** [nbrightproject/NBrightBuy#32]
Dave,

As I mentioned in a previous issue, I've made a copy of the ClassicRazor so I can create my own design.

It mostly seems to work fine, except the basket in the MiniCart is not updating when an item is added. It is being added to the basket ok, it's just the minicart details aren't changing.

I'm guessing it may be simple if you could point me in the right direction.

John

PS. Love the new product.

**Comment by leedavi** [comment]
This should work by ajax and the ajax should return the mini cart html to a specific html element, this is specified in the NBS_MniCart_head.cshtml.

```
    $('.addtobasket').click(function () {
        //if (form.valid()) {
            nbxget('addtobasket', '.entryid' + $(this).attr('itemid'), '#minicartdatareturn'); // Reload Cart
            $('.addbasketmsg' + $(this).attr('itemid')).delay(10).fadeIn('fast');
        //}
    });

    $('#minicartdatareturn').change(function () {
        nbxget('rendercart', '.minicartdata', '.container_classicrazor_nbs_minicart'); // Reload Cart
        $('.addedtobasket').delay(1000).fadeOut('fast');
    });
```

In this case the nbxget function is returning data to a html element that has a class of "container_classicrazor_nbs_minicart", the third param is the return element as a Jquery selector.  Maybe you need to make sure the minicart has this class on it or alter the Jquery selector in the JS.

**Comment by micahsdad1402** [comment]
When I inspect the page, the div has a class of .container_grt.razor_nbs_minicart.

This is also what the above Jquery has.

However I can't find where the class is attached to the div in the code.

If I change the Jquery back to .container_classicrazor_nbs_minicart it still doesn't work, and when I do the inspect the class is still .container_grt.razor_nbs_minicart.

I"m just wondering if have a "." in the name is causing this issue?

**Comment by leedavi** [comment]
That would be my guess, the . is an identifier for jQuery, so it could be the cause, can you try it with a _ instead?

**Comment by micahsdad1402** [comment]
That was it.
