### ISSUE TITLE
Shipping method. Checkout step problem 

### ISSUE THREAD

**Issue by alx726** [nbrightproject/NBrightBuy#47]
Dear Sir!
I'm trying to develop my own Shipping provider, I took default shipping provider as base and it works, but now I need to add custom checkout options at the stage Summary ("Order process"->"Basket"->"Addresses"->"Summary") (like Chronopost). Could you provide any ideas or a parts of the Cronopost Shipping Provider c# / html/xml code

Thanks for your help.

**Comment by leedavi** [comment]
Hi, I've moved the chronopost source to github.
https://github.com/nbrightproject/NBrightBuyChronopost

**Comment by alx726** [comment]
Thanks a lot!
