### ISSUE TITLE
Sort on properties

### ISSUE THREAD

**Issue by MartyNZ** [nbrightproject/NBrightBuy#5]
I didn't get an answer on this before David closed the previous issue. Perhaps I didn't ask clearly enough.
I have figured out how to create a property, and add that property to a product. I can filter on that property in the ProductView module. What I want to know is how I can sort on the property in product view. The goal being to sort so that items 'For Sale' are listed before items 'Sold' in the product view.
Is this possible?

cheers
MartyNZ

**Comment by leedavi** [comment]
um!!. the quick answer is no.
Althought there is room for bespoke sort filters on the product list template  look at the {bycategoryproduct} token.

http://nbsdocs.nbrightproject.org/Documentation/TagTokens/TabId/424/eid/7106/modid/917/orderby.aspx

Although this might be a little complicated to get right.  The easy way which we use is to have multiple product list modules on the page, even one displaying on 1 type of property.

**Comment by leedavi** [comment]
The only alternative is a bespoke module which uses it's own sort criteria.  I've done this for a client with complicated sort patterns and it's probably easier that trying to make the default module do something it's not designed to do.
