### ISSUE TITLE
Regions not working properly with saved addresses

### ISSUE THREAD

**Issue by micahsdad1402** [nbrightproject/NBrightBuy#50]
There is an issue with how the region works on the address stage of the checkout.

Firstly, it wasn't saving the region to the userdata for the user, 

I fixed this in the NBS_CheckoutAddress.cshtml by updating the following code and adding region to it.

` @if (info.UserId >= 0)
    {
        <div class="formrow">
            <h6>@ResourceKey("General.ChooseAddress")</h6>
            @AddressSelectList(info,"genxml/dropdownlist/selectaddress", ".checkoutbillform", "firstname,lastname,company,unit,street,postalcode,city,country,telephone,email,region", "class='chooseaddress'")
        </div>
    }

So now the region/state is saved, but when the address is selected it isn't returned.

I had a bit of a look but couldn't really work it out.

It also keeps adding addresses to the saved addresses because of this.

One other thing, if there is a saved address, it would be good to preselect it rather than having to select the address each time. If there is more than one address, you could have it selected as default shipping, or default billing etc.

Another nice to have would be to be able to change the label, particularly for Region, based on the country selected. not sure how hard this would be. For example in Australia you would use States, rather than region, and UK, it would be Counties. 

I just installed the AddressAdmin module. It's not displaying regions on the first page. Also, I can't see how to change the primary address.

**Comment by leedavi** [comment]
Hi,
Yes, becuase the region needs to have the country dropdown selected before it populates there's a race condition on th rendering of the address.  And unfortunatly the quick and easy solution is to do what I've done!  Make the client selected the region on each checkout, even when they select an address.

Hopfully at somepoint we'll work out the logic and process to make this work better.

To change the label, just create a General.resx for Australia and add the lblregion.Text in there to use State.

With the default address this is a flag.  I don;t know why, but it does appear that this is not exposed on the interface.  Again this is something we probably need to look into.

**Comment by micahsdad1402** [comment]
I've made some changes so that there is a "Make Default" button in the Edit Addresss, and it's working well if you are interested in me contributing this to your project. 
I found another small bug where the Region field isn't populated when you edit the Primary Address, but works with Optional Addresses. Just trying to work that one out now.

**Comment by leedavi** [comment]
yep great, create a pull request with your changes.

**Comment by micahsdad1402** [comment]
I updated the address again with the region, and then it started working. May have been something funny with DNN profile.

However I have found an issue where you can't update firstname on the Primary Address. It never saves.Last name does though

**Comment by leedavi** [comment]
Hi, not sure what's wrong here!  I've tested on my system and it works OK.  have you change the address templates?
