### ISSUE TITLE
Trimming the BackOffice view by Permission

### ISSUE THREAD

**Issue by ergodaveh** [nbrightproject/NBrightBuy#51]
We have the V3.5 running on DNN8  and would like to trim the Backoffice functionally by a User's permission.    The target use case is such that a security role called ProductRep would have a product view within BackOffice excluding other views available to the ManagerRole or EditorRole.  
We had noticed there is some code commented referring the Client role
// anyone only in the client role is only allowed in the products control
                    if (UserInfo.IsInRole(StoreSettings.ClientEditorRole) && (!UserInfo.IsInRole(StoreSettings.EditorRole) 
                        && !UserInfo.IsInRole(StoreSettings.ManagerRole) 
                        && !UserInfo.IsInRole("Administrators")))
                    {
                     //   ctrl = "products";
                    }
Does this accomplish our target use case?

**Comment by leedavi** [comment]
This is an area I hope to tidy up a little and make more flexible.  But for now yes, this clientrole option should allow you some control from for this use case.  Although the actual role is hardcoded for now..

```
    public const String ManagerRole = "Manager";
    public const String EditorRole = "Editor";
    public const String DealerRole = "Dealer";
    public const String ClientEditorRole = **"ClientEditor";**
```

You'll may also want to play with the role restrictions in the Admin>plugins, there is a field you can restrict display of certain options.

**Comment by ergodaveh** [comment]
Thanks for the reply.

Here are our steps followed to trim the BackOffice<using ClientEditor>

Added the new security role called 'ClientEditor' to the website
Applied the 'ClientEditor'  role to  the targetUser

Edited the Admin>plugin Products  to include the Security Role 'ClientEditor'

Cleared cache

Restarted App pool

<went for coffee> :)

Unfortnately, All attempts by the User to access the Products 'Add' function resulted in an error<as seen below>

TabId:

PortalAlias:localhost:3033

OriginalUrl:/Error.aspx

Referer:http://localhost:3033/Admin/NBS-Back-Office/ctrl/products

Url:http://localhost:3033/Error.aspx

UserAgent:Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393

HostAddress:::1

HostName:::1

Server Name: happyServer

We did try the same scenario with the 'Editor' role included in the User account.

The Add function successfully rendered.  However, the Users profile had access to other menu items such as Vouchers

Cheers,

Dave

**Comment by leedavi** [comment]
OK, off the top of my head I can;t remember the exact use case for the clienteditor, but it could not to allow add.  It should not throw an error and we might have to look at that.

However, why don;t you assign Editor roles to the user and simply remove the editor role from the voucher plugin?
