### ISSUE TITLE
Tax

### ISSUE THREAD

**Issue by micahsdad1402** [nbrightproject/NBrightBuy#53]
How do I configure the tax so that customers from Australia are taxed, and everyone else is tax exempt?
Tried some different options on the settings and all it did was removed the tax for Australia.

**Comment by leedavi** [comment]
you need to use the exempt tax option..
![capture](https://cloud.githubusercontent.com/assets/5583141/18740797/e6f38180-80ab-11e6-93ec-4d173cc2aa22.PNG)

**Comment by micahsdad1402** [comment]
OK. I worked that out. But the problem is I either need to list every country except AU in the exempt list, or limit the countries I can sell too. The NBS 2 had an option where you could list the counties that are taxed, and everything else wasn't. This is true for at least NZ and AU,

Also, with Tax Exempt countries it put the amount with tax removed in the basket, but then when it displayed the basket should the full amount, and it wasn't until you get to the Summary that it displays the tax removed. Is this something I can do with the templates?

**Comment by leedavi** [comment]
Sorry, i made a miostake on the screen shot, I put the countries under the Taxed region code list.  this doesn't do anything it's only the checkbox you need.  But it will check the tax against the store country in the merchant address.  So Clear out all the EU countries (the tax provider is deisgned for EU use mainly) from the EU tax box, you don;t need them and it may cause issues.

Clear down the regional tax field

Make sure exempt is checked
 and make sure you merchant country in the merchant address is set to AU.

Now with the tax showing on the cart, the trouble is we don't know the country until you get to the address and fill in the country, so the tax calc cannot be done until you reach the summary!

**Comment by micahsdad1402** [comment]
Thanks. That's now working

**Comment by micahsdad1402** [comment]
Thanks this sorted it.
