### ISSUE TITLE
Feature Properties

### ISSUE THREAD

**Issue by micahsdad1402** [nbrightproject/NBrightBuy#55]
Dave,
I'm keen on using the Feature Properties. 

However I see that the Product Display isn't yet setup to show these.
I'm happy to develop this but what I can't find in the database is where the Products are linked to the features. I can find the features, and the products, but not the link between them. I'm sure it's there somewhere!

**Comment by leedavi** [comment]
Properties are just categories under a different UI name and with no tree stucture.
Look at the eid in the url to find the record int he DB.

**Comment by leedavi** [comment]
You've got a @PropertyValue razor token in NBrightBuyRazorTokens.cs

**Comment by micahsdad1402** [comment]
I can find the property in the db no problems,  and I understand it's a category. What I can't find is where the product-property link is.
What I want to do is use this to display product features because I sell three antivirus products,  and the they each have features in common,  with additional features for each level of product.
I would assume best place to put these is on a tab.

**Comment by leedavi** [comment]
The system creates a cross ref record "CATXREF" and uses the xrefitemid and parentitemid files to link the data.  Just like a standard relational database, it's just that I've created what could be termed as a object database in a the DNN DB.  All data is in NBrightBuy table, the other tables are just for indexing and speed which gets over the limitation in indexing XML record.

**Comment by micahsdad1402** [comment]
Got it working... just need to make it pretty with css
I add the following bits to NBS_ProductDiscplayDetail.cshtml:

`@if (product.GetCategories("fea").Count > 0)
                    {
                        <li><a href="#tab-4">@ResourceKey("ProductView.features")</a></li>           
                    }`

`@if (product.GetCategories("fea").Count > 0)
            {
                <div id="tab-4" class="tab-content tab-hide">
                    <h3>@ResourceKey("ProductView.features")</h3>
                    <div class="features" style="display:table">
                                                                
                                @foreach (GroupCategoryData f in product.GetCategories("fea"))
                                {                   
                                    <div class="feature-item" style="display:table-cell">                     
                                        <div class="feature-name" style="display:table-cell"><h4> @PropertyValue(f,"propertyname")</h4> </div>                                    
                                        <div class="feature-detail" style="display:table-cell"> @PropertyValue(f,"propertydesc") </div>  
                                    </div>
                                }                                
                    </div>
                </div>            
            }`
