### ISSUE TITLE
Models Not working correctly in tab

### ISSUE THREAD

**Issue by micahsdad1402** [nbrightproject/NBrightBuy#56]
The NBS_ProductDisplayDetail.cshtml template doesn't work for models.
1. It displays the product best price, not the model best price
2. Because it's a table, when it tries to show on a screen of less than 991px width, the whole Product Detail disappears because of this CSS line .productdetail {overflow:hidden;line-height:normal;}

I actually don't need this so will just remove the tab from my template.

I also found a problem with this line of code 

`if (product.Models.Count >= 1 && product.Options.Count >= 1)`

it should be

`if (product.Models.Count >= 1 || product.Options.Count >= 1)`

**Comment by leedavi** [comment]
OK, I'll have a word with designer about this.  I know this theme was created for a specific responsive skin, maybe we need to adapt for the default release.

I'll fix the razor test for the next release.

**Comment by micahsdad1402** [comment]
In the end I just removed the CSS for overflow:hidden. After I removed the models, it still happened. I think this was related to where I had the mini cart. I'm just trying to get it all going then will finesse the responsive stuff later.
