### ISSUE TITLE
More info on the ListView Grid

### ISSUE THREAD

**Issue by in8dna** [nbrightproject/NBrightBuy#58]
I'm trying to add more information about an item in each of the GridView cells from product information entered in Admin. For example we'd like to display the SEO TITLE data below the ProductName.
![image](https://cloud.githubusercontent.com/assets/13932030/18971752/1fb24b60-864b-11e6-8b84-302018935445.png)
Right now I have added a line to the NBS_ProductDisplayList.cshtml template line 111 like this:
`<div class="description">
                        <h4><a href="@EntryUrl(info,Model)">@ProductName(info)</a></h4>
                        <h6>@ProductName(info)</h6>`
My question is;"what can I do to pull the SEOTITLE data into the heading 6 location?"

I've tried scouring the code, and random variations like '@SEOTitle(info)' without luck.

**Comment by leedavi** [comment]
you can use the direct GetXmlProperty function and just use the xpath to the field, in this case:

@info.GetXmlProperty("genxml/lang/genxml/textbox/txtseoname")

Same goes for any other field in the product XML

**Comment by in8dna** [comment]
# Thank you -

`
1  @info.GetXmlProperty("genxml/lang/genxml/textbox/txtseoname")

2  @info.GetXmlProperty("genxml/lang/genxml/textbox/txtseopagetitle")

3  @info.GetXmlProperty("genxml/textbox/txtproductref")`

![image](https://cloud.githubusercontent.com/assets/13932030/19003135/573ffa8c-8704-11e6-9c72-b1fd300ee64a.png)
