### ISSUE TITLE
Creating Categories & Page Redirection

### ISSUE THREAD

**Issue by chrissieq** [nbrightproject/NBrightBuy#6]
Hi David

I'm still having 500 errors. This time when I try to create a category. I can assign products, but can't save any other details such as name, code etc.

Also, page redirection is not working on min-cart and basket. The module settings appear correct, but the tabid in the url seem not to have aligned

Kind regards
Christine

**Comment by leedavi** [comment]
Those setting are all setup in the Back Office>Admin>Store Config section, make sure you save those.

**Comment by chrissieq** [comment]
Checked those and they seem to be ok
