### ISSUE TITLE
Broken links after last update

### ISSUE THREAD

**Issue by dvdobrovolskiy** [nbrightproject/NBrightBuy#61]
Links to product detail show error now
system.collections.generic.keynotfoundexception:%20The%20given%20key%20was%20not%20present%20in%20the%20dictionary.%20%20%20at%20System.Collections.Generic.Dictionary`2.get_Item(TKey%20key)%20%20%20at%20Nevoweb.DNN.NBrightBuy.Components.NBrightBuyUtils.GetEntryUrl(Int32%20portalId,%20String%20entryid,%20String%20modulekey,%20String%20seoname,%20String%20tabid,%20String%20catid,%20String%20catref)%20%20%20at%20NBrightBuy.render.NBrightBuyRazorTokens`1.EntryUrl(NBrightInfo%20info,%20NBrightRazor%20model,%20Boolean%20relative,%20String%20categoryref)

here is sample
http://v2.stroy-svet.ru/ru/

**Comment by leedavi** [comment]
did you load the new template system v8.1.1?

Also go into the store settings, make sure all the pages are correct for the store and do a save of the settings.  Then restart the app, to be sure and test it again.

**Comment by dvdobrovolskiy** [comment]
NBrightTemplateSys   is 8.1.1

Pages seems OK. Saved. Restarted

Same situation.
system.collections.generic.keynotfoundexception:%20The%20given%20key%20was%20not%20present%20in%20the%20dictionary.%20%20%20at%20System.Collections.Generic.Dictionary`2.get_Item(TKey%20key)%20%20%20at%20Nevoweb.DNN.NBrightBuy.Components.NBrightBuyUtils.GetEntryUrl(Int32%20portalId,%20String%20entryid,%20String%20modulekey,%20String%20seoname,%20String%20tabid,%20String%20catid,%20String%20catref)%20%20%20at%20NBrightBuy.render.NBrightBuyRazorTokens`1.EntryUrl(NBrightInfo%20info,%20NBrightRazor%20model,%20Boolean%20relative,%20String%20categoryref)

**Comment by leedavi** [comment]
OK, at a guess it seems to be misisng some tab setting.  Make sure you have all the tabs settings selected in the Module Settings and in the BO>Admin>Settings.

If you still have the problem PM me a login and I'll have a look to see if I can see anything.

**Comment by dvdobrovolskiy** [comment]
doh! yeah, module settings. Now all ok. Many thanks
