### ISSUE TITLE
Product option not carrying across

### ISSUE THREAD

**Issue by DigitalTrading** [nbrightproject/NBrightBuy#62]
We've added an option to a product which has no values, on the front end it shows a textbox that allows the user to enter their own option value. However this value doesn't get passed across to the cart/order. It doesn't appear on the front end or in the XML in the database.

**Comment by leedavi** [comment]
I've just done a test on my dev system and it's all working correctly.

the textbox data should appear on the order item.

Have you got a url I could look at?  PM me a login if you have and I'll take alook.

**Comment by DigitalTrading** [comment]
Hi Dave,
If you go to this pages:
http://partid.digitaltradingco.co.uk/Shop/Product-Details/catid/22/eid/3232/circus-sweet-cone
you will see 3 options:

> Gender for special sticker (this is a drop down)
> Age for special sticker (this is free type)
> Name (this is free type)

If you enter values into these options and add to basket. Go to the baket and you will see the description plus the values in the drop down attributed to each option and not the values entered into these fields.

If you need access to the backend please PM me and I will create you an account.
