### ISSUE TITLE
Confirmation mail not localized

### ISSUE THREAD

**Issue by Tychodewaard** [nbrightproject/NBrightBuy#64]
After an order 2 mails are being sent: manager and the customer.

The mail to the manager is in the localized language. The mail to the customer is in English.
This should be the localized version.

**Comment by leedavi** [comment]
The client email should be sent in the same language was made in, was the order made while in English?

**Comment by Tychodewaard** [comment]
Nope. In this shop NL is the only language.

**Comment by leedavi** [comment]
The language for the email is taken from the orderdata 

SendEmailOrderToClient(....

 var lang = ordData.Lang;

This should be set by the payment gateway, which gateway are you using?

**Comment by leedavi** [comment]
No, Sorry.  I'm wrong is saying that it is the payment provider.  It should be set when you place the order  and should be the current language.

```
                    _cartInfo.Lang = Utils.GetCurrentCulture();  // set lang so we can send emails in same language the order was made in.
```

So I'm a little surprise you getting the wrong language if you only have NL?

**Comment by leedavi** [comment]
OK, I've trace the code and it all looks to be setting the correct language.  Maybe the new ajax call in the checkout is losing the session data and therefore language, which i know can happen.

I'll do some tests and try to recreate this issue.

**Comment by Tychodewaard** [comment]
I'm using the Mollie payment, maybe that's different from your setup. Weird thing is, I have manually overwritten the resx files for default and GB-UK to Dutch and it still keeps thanking me in English. If you want, I can give you FTP access.

**Comment by leedavi** [comment]
GB-UK doesn;t exist.   It's en-GB.  But it sounds like it's picking up the defaut resx, as if it doesn;t know which language to take.  I'm working on this area today, I'll check to see if I can understand why this is happening for you.

**Comment by leedavi** [comment]
OK, I've trace the code.  The user profile of the user who created the order overwrites the order langauge when sending an email.

```
        var lang = ordData.Lang;
        if (ordData.GetInfo().UserId > 0)
        {
            // this order is linked to a DNN user, so get the order email from the DNN profile (so if it's updated since the order, we pickup the new one)
            var objUser = UserController.GetUserById(ordData.PortalId, ordData.GetInfo().UserId);
            if (objUser != null)
            {
                if (ordData.EmailAddress != objUser.Email)
                {
                    ordData.EmailAddress = objUser.Email;
                    ordData.SavePurchaseData();
                }
                if (objUser.Profile.PreferredLocale != "") lang = objUser.Profile.PreferredLocale;
            }
        }
```

Is the prefered langauge of the user who created the order is English?

**Comment by Tychodewaard** [comment]
In my test scenario the user is without profile. If I start a purchase in a incognito tab, not logged in and using the Dutch shop (lang parameters nl-nl) the confirmation email is in English.

When I am logged in and set my preferred language on Dutch, it gives me the Dutch order cornfirmation.

Apparently anonymous users don't have a preferred language in DNN (understandable) and it falls back to system default (US).
I now editted /DesktopModules/NBright/NBrightBuy/App_LocalResources/Notification.ascx.resx with Dutch notes which helps me out for now. And which makes this issue less critical as there is a workaround. But still a wish :-)
