### ISSUE TITLE
Improved Dutch language pack

### ISSUE THREAD

**Issue by Tychodewaard** [nbrightproject/NBrightBuy#65]
Hi Dave

The default language pack for NL creates a great start, but I made some enhancements.
Attached the language files. I created these through the DNN wizard. 

If I need to do this differently, please let me know.

Tycho

[ResourcePack.NBS_AddressAdmin.3.5.1.nl-NL.zip](https://github.com/nbrightproject/NBrightBuy/files/517618/ResourcePack.NBS_AddressAdmin.3.5.1.nl-NL.zip)
[ResourcePack.NBS_CategoryMenu.3.5.1.nl-NL.zip](https://github.com/nbrightproject/NBrightBuy/files/517622/ResourcePack.NBS_CategoryMenu.3.5.1.nl-NL.zip)
[ResourcePack.NBS_Checkout.3.5.1.nl-NL.zip](https://github.com/nbrightproject/NBrightBuy/files/517623/ResourcePack.NBS_Checkout.3.5.1.nl-NL.zip)
[ResourcePack.NBS_DisplaySearch.3.5.1.nl-NL.zip](https://github.com/nbrightproject/NBrightBuy/files/517619/ResourcePack.NBS_DisplaySearch.3.5.1.nl-NL.zip)
[ResourcePack.NBS_FullCart.3.5.1.nl-NL.zip](https://github.com/nbrightproject/NBrightBuy/files/517620/ResourcePack.NBS_FullCart.3.5.1.nl-NL.zip)
[ResourcePack.NBS_MiniCart.3.5.1.nl-NL.zip](https://github.com/nbrightproject/NBrightBuy/files/517621/ResourcePack.NBS_MiniCart.3.5.1.nl-NL.zip)
[ResourcePack.NBS_OrderAdmin.3.5.1.nl-NL.zip](https://github.com/nbrightproject/NBrightBuy/files/517627/ResourcePack.NBS_OrderAdmin.3.5.1.nl-NL.zip)
[ResourcePack.NBS_Payment.3.5.1.nl-NL.zip](https://github.com/nbrightproject/NBrightBuy/files/517624/ResourcePack.NBS_Payment.3.5.1.nl-NL.zip)
[ResourcePack.NBS_ProductDisplay.3.5.1.nl-NL.zip](https://github.com/nbrightproject/NBrightBuy/files/517626/ResourcePack.NBS_ProductDisplay.3.5.1.nl-NL.zip)
[ResourcePack.NBS_ProfileForm.3.5.1.nl-NL.zip](https://github.com/nbrightproject/NBrightBuy/files/517625/ResourcePack.NBS_ProfileForm.3.5.1.nl-NL.zip)

**Comment by leedavi** [comment]
Hi Tyco,
Can you zip all the changed resx files into 1 zip file and send it to me, I'll include it in the next release.

**Comment by Tychodewaard** [comment]
You got it.
