### ISSUE TITLE
Sales - Orders can be broken

### ISSUE THREAD

**Issue by Tychodewaard** [nbrightproject/NBrightBuy#66]
In the Back office there is Sales and within that 'Orders' .
I pasted a voucher code in the search box (was looking for the order that used that promotion code) and this creates an error. This error remains there even after empty cache or restart application.

There is no error after starting an incognito session in Chrome. So it's not entirely wrecked :-)

In ordere of importance:
- It would be nice to not break when searching on a promotion code
- It would be even nicer if one could search on promotion code in case people call "My promotion code doesn't work". That way the shop manager can track down who/when the code was used.

The error:

System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '1'. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() at System.Data.SqlClient.SqlDataReader.get_MetaData() at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) at System.Data.SqlClient.SqlCommand.ExecuteScalar() at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteScalar(SqlConnection connection, CommandType commandType, String commandText, SqlParameter[] commandParameters) at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteScalar(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters) at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteScalar(String connectionString, String spName, Object[] parameterValues) at Nevoweb.DNN.NBrightBuy.Components.SqlDataProvider.SqlDataProvider.GetListCount(Int32 portalId, Int32 moduleId, String typeCode, String sqlSearchFilter, String typeCodeLang, String lang) at Nevoweb.DNN.NBrightBuy.Admin.Orders.PageLoad() at Nevoweb.DNN.NBrightBuy.Admin.Orders.OnLoad(EventArgs e) ClientConnectionId:ba76fe49-e3b1-4fc7-af12-b4cc5b495280 Error Number:102,State:1,Class:15

**Comment by leedavi** [comment]
Hi Tyco,

I've not seen this before.  It looks like we've introduced a bug with a previous release.

If you use the reset button it should clear the error.

I'm currently rebuilding  the order admin to use Ajax, which will make it possible to remove the current SQL build method and hence fix this problem.

I'll see if it's possible to do a search on the promotion code as well.
