### ISSUE TITLE
Model should be optionally required

### ISSUE THREAD

**Issue by Tychodewaard** [nbrightproject/NBrightBuy#69]
If you have multiple models from 1 product, it would be great to be able to force to select a model. This could be done by:
- select no model by default (now, it's always the first model)
- check of model is selected, if not: alert box "please select a model"

**Comment by leedavi** [comment]
A product must have at least 1 model to be able to add to the basket.

If you want just to force a selection from the client by having a blank option, this could be done in the template by using JS and is not something that would need any code changes.
