### ISSUE TITLE
Sub-Menu Option Missing from ProductDisplay

### ISSUE THREAD

**Issue by qualitymanager** [nbrightproject/NBrightBuy#70]
In the old nbstore there were options to show a submenu in the product display module (and some styling options for it). This allowed the sub categories of the current category to be shown below the current categories message.

This option is no longer present in NBrightBuy.

I assume this would have to be coded directly into NBS_ProductDisplayList.cshtml but i am also assuming that the Model of this view is a list(of article) and doesnt have the category list (thus not accessible to the razor template)?

If so is there any way you could show an example of how to do something similar to the previous sub-menu feature either with existing release code or "broadly speaking" which files would need modifying to include the list of categories in the model such that the razor template could then be modified to support this functionality.

As to why: We use this method to navigate the store by category (current cat message + list of sub cat images) in preference to the categorymenu module.

**Comment by leedavi** [comment]
There is a razor token called @CategoryDrillDown that you can use to do this.

```
    public IEncodedString CategoryDrillDown(int parentCatId, string razorTemplate, string controlPath, string theme, int currentCatId, string lang, int tabid, string itemClass = "drilldownitem")
    {
        var catBuiler = new CatMenuRazorBuilder(razorTemplate, controlPath, theme, currentCatId, lang);
        var strOut = catBuiler.GetDrillDownMenu(parentCatId, tabid, itemClass);
        return new RawString(strOut);
    }
```

You'll need to pass a razortemplate to it, 

<div class="drilldownlist">
    @CategoryDrillDown(catid, "NBS_CategoryMenuDrillLink.cshtml", "/DesktopModules/NBright/NBrightBuy", Model.GetSetting("themefolder"), catid, Utils.GetCurrentCulture(), tabid) 
</div>

You can also use the NBS_CategoryMenuDrill.cshtml template in the category menu module.

**Comment by qualitymanager** [comment]
just changing ListTemplate to NBS_CategoryMenuDrill.cshtml results in empty module and i dont really understand how to use the other solution as im not really a razor guy.

I tried taking a usage of getting catid and tabid from another template and using them in the method call you listed (i put the code below just above the "product list body" loop in the template line 57 in the installed template) but it results in System.InvalidOperationException: The same key was already used for another template...

I dont really know if that is how or where you had in mind for using it? 
Any chance you could advise or attach an altered NBS_ProductDisplayList.cshtml template

`@{
            var catid = 0;
            if (Utils.IsNumeric(Model.GetUrlParam("catid")))
            {
                catid = Convert.ToInt32(Model.GetUrlParam("catid"));
            }
            var tabid = Model.GetSettingInt("productlisttab");
            if (tabid <= 0)
            {
                tabid = StoreSettings.Current.ProductListTabId;
            }
            CategoryDrillDown(catid, "NBS_CategoryMenuDrillLink.cshtml", "/DesktopModules/NBright/NBrightBuy", Model.GetSetting("themefolder"), catid, Utils.GetCurrentCulture(), tabid);
        }
`

**Comment by leedavi** [comment]
That's a error message about the razor caching.  Put the store in debug mode if your editing templates or restart the app each time you change.
