### ISSUE TITLE
redirect after add to basket

### ISSUE THREAD

**Issue by Tychodewaard** [nbrightproject/NBrightBuy#71]
I don't know whether this is a question (maybe it already exists but I couldn't find it) or a feature request. But I'd like to be able to set the action after I add a product to the basket: either the current toaster or redirect to the checkout page.

**Comment by leedavi** [comment]
In the "NBS_MiniCart_head.cshtml" template there is an event for after add to basket.

this updated the mini basket, you can either replace that with the redirect you  or add another JS event to do some operation after the minicart is updated.

```
    $('#minicartdatareturn').change(function () {
        nbxget('rendercart', '.minicartdata', '.container_classicrazor_nbs_minicart'); // Reload Cart
        $('.addedtobasket').delay(1000).fadeOut('fast');
    });
```

if you want to do an event after the mini cart update, create a JS event on the mini cart change, like this:

```
    $('.container_classicrazor_nbs_minicart').change(function () {

    });
```

**Comment by leedavi** [comment]
rememebr this is razor, so you can pickup the storesetting to redirect to the checkout page, you don;t have to hard code it.

**Comment by Puppyknucks** [comment]
@leedavi as a self taught novice I appreciate that it looks like this is a very easy solution, unfortunately I do not understand what i need to do...

**Comment by leedavi** [comment]
It's a little difficult to explain JS and JQuery events in a post, it can take hours and hours of testing and playing with silly html/jquery scripts to get a fully understanding.  But the basic principle is that when you've added something to the basket, it will trigger an event on the browsers which can be pickup up and an action done.   

for instance

$('.container_classicrazor_nbs_minicart').change(function () {
    window.location.href = 'http://nbs3.nevoweb.com/fr-fr/Basket';
 });

Will do a redirection to the basket of the demo site after the minicart is updated.  i.e. after an add to basket.  But there are also considerations of when this event is defined and when it is triggered.

https://api.jquery.com/category/events/

You can alter the template for do a lot, and combined with razor there is lot more functionality available.

**Comment by Puppyknucks** [comment]
I assume I would change nbs3.nevoweb.com to my basket url but where would I place this code?

**Comment by leedavi** [comment]
Try in the "NBS_MiniCart_head.cshtml" just after the addtobasket click event.

**Comment by Tychodewaard** [comment]
I tried below but that's not doing it. (Sorry, for the n00b-question)

```
   $('.addtobasket').click(function () {
        //if (form.valid()) {
            nbxget('addtobasket', '.entryid' + $(this).attr('itemid'), '#minicartdatareturn'); // Reload Cart
            $('.addbasketmsg' + $(this).attr('itemid')).delay(10).fadeIn('fast');
        //}
    });

    $('#minicartdatareturn').change(function () {
        nbxget('rendercart', '.minicartdata', '.container_classicrazor_nbs_minicart'); // Reload Cart
        $('.addedtobasket').delay(1000).fadeOut('fast');

    $('.container_classicrazor_nbs_minicart').change(function () {
        window.location.href = '/Checkout';
    });
```

**Comment by dnnconsulting** [comment]
For other people interested in this, this is how to redirect the user to the basket page when they click the buy button:

Alter the NBS_MiniCart_head.cshtml file:

`$('.addtobasket').click(function () {
            //if (form.valid())
            var basketUrl = "/tabid/" + @Model.GetSetting("carttab") + "/Default.aspx";
            window.location.href = basketUrl;
            nbxget('addtobasket', '.entryid' + $(this).attr('itemid'), '#minicartdatareturn'); // Reload Cart
            $('.addbasketmsg' + $(this).attr('itemid')).delay(10).fadeIn('fast');
            //}
        });`

Regards,
Geoff

**Comment by Tychodewaard** [comment]
Hi Geoff, 

Thanks for giving it a spin!

I just tried that but that doesn't work for me. It looks like too much code is uncommented (is that a word? I mean 'made a comment') . It now doesn't do anything in my setup.

**Comment by dnnconsulting** [comment]
Hi Tycho,

The code does work or you have not understood correctly.

As for the comments, I haven't added any, this is the original code and the other thing I have added is 2 extra lines of code to the function above.

The 2 lines are:

`var basketUrl = "/tabid/" + @Model.GetSetting("carttab") + "/Default.aspx";`
and 
`window.location.href = basketUrl;`

The rest is un-altered.

Regards,
Geoff

**Comment by Tychodewaard** [comment]
To wrap this up: the redirect is now working. There has been some changes as a js conflict caused troubles in Safari (iPhone and Mac). Is it possible to publish that piece of code (or the adjustments) here? 

I'll close this one for now, additions can be posted after that.
