### ISSUE TITLE
Intended use of Properties / Property Groups

### ISSUE THREAD

**Issue by qualitymanager** [nbrightproject/NBrightBuy#72]
Im trying to understand the intended usage of properties and apart from the documentations brief description on thier use for searching im not sure of thier other potential uses. 

For instance, in the default installation there is a property called "Manufacturer".
If i add two properties to this property Manufacturer1 and Manufacturer2, these can be selected for an article and saved, all good so far.

My initial thoughts were that these could be used in a similar fashion to custom fields, so i could create a list of manufacturers and select the appropriate one from the list in the article editor, then in the template have the selected value shown in product views.

Is this an intended (or potential) use? or are they intended to be used for searching only?

If i can create the list and show the selected value, how do i do that in a razor template?

**Comment by leedavi** [comment]
The idea of properties, is mainly for searching.  The idea is a filter system can be created for products with certain properties.  There is also the concept that products with properties can have an effect on the razor layout where products can be tested for certain properties, use the "HasProperty" method of the productdata class.
You can also user the "GetProperties" method to get a list of properties and then build that list on the product display.  Although the potential for passing this back to the basket is limited, but not impossible.

Basically, properties are very useful for bespoke system.  We at Nevoweb use NBS as a base for our bespoke index/directory systems and as such this property feature is very useful. For a normal e-commerce that is using the standard ClassicRazor templates the usefulness is limited, unless you start creating bespoke solution's and filters for your clients.

To give you an understanding of properties, technically there is no difference between categories and properties, they are stored the same on the database.

In future I'll see if we can create a generic filtering system based on properties people can use.

**Comment by qualitymanager** [comment]
Thanks for the explanation. 
I've found out how to do what i was looking for and although its not strictly the intended use of properties it might be useful for anyone else interested in something similar. 

I wanted to create a list of Disclaimers that our non technical store manager could add to then attach to relevant products and have shown on the product display (without technical assistance from me once the template was created). Here is how i did it.

BO | Admin | Property Groups 
Add : Type: Disclaimers, Ref : **dis**

BO | Properties | Disclaimers | 
Add : Ref : Standard, Name: Image for illustrative purposes only, actual product appearance may differ.
Add : Ref : Legal, Name: Some Legal Blurb

BO | Catalog | Articles | <appropriate product> | Poperties
Disclaimers : Image for...
Disclaimers : Legal...
Save

Source | NBS_ProductDisplayDetail.cshtml

Show first instance of property found:
`<div itemprop="disclaimers" class="disclaimers">@PropertyValue(product, "**dis**", "SEOName", 0)</div>`

Show all instances (all values) of a property group/type found:
`@{List<GroupCategoryData> disclaimers = product.GetProperties("**dis**", true); }
            <div itemprop="disclaimers" class="disclaimers">
                @foreach (GroupCategoryData disclaimer in disclaimers)
                {
                    <div class="disclaimer">@disclaimer.seoname</div>
                }
            </div>`

**Comment by leedavi** [comment]
OK, good example of possible usage.
I think you could have used "categoryname" instead of "SEOName"
