### ISSUE TITLE
Adding custom fields with titles on select articles - for a self taught novice

### ISSUE THREAD

**Issue by Puppyknucks** [nbrightproject/NBrightBuy#73]
I sell engravable pet ID tags and would like to add a box for an engraving request on the product details page, if someone chooses to have an item engraved. 
IE:
Engraving 1st line, 10 characters
_field_
Engraving 2nd line, 10 characters
_field_

I hate that I am self taught and am still learning and I apologize if any of my questions seem remedial and I appreciate as many details and specifics as you can offer.

**Comment by leedavi** [comment]
If you create an option on a products and give it no values it will create a textbox on the product detail, which can by used for you engraving text.

You'll need to put some validation on those textboxes to ensure you only get a limited number of characters.

 There should already be "jquery.validate.min.js" injected, so you can use that. Sorry I don;t have any examples at hand.

https://jqueryvalidation.org/documentation/

**Comment by Puppyknucks** [comment]
I created option 'Engraving= 2 lines 10 characters each' and gave it 2 values. both values were blank at 0.00 extra cost. Noting showed up on the site.
I added values and extra costs but it still does not show on the site. which leads me to believe I can only add 1 option which I had already done. can you confirm?

**Comment by leedavi** [comment]
Not sure  what your doing.  But you can add as many options and option values as you want.

Whatyou need is 2 options with no option values.

If you saying nothing appear on you site? then are you looking at the detail view?

**Comment by Puppyknucks** [comment]
It is partially working...

![engraving details](https://cloud.githubusercontent.com/assets/22919237/19541470/2f572b12-962c-11e6-9105-21acf04a80f2.JPG)
![engraving settings](https://cloud.githubusercontent.com/assets/22919237/19541471/2f5aa418-962c-11e6-988c-7a757ccbdabb.JPG)
