### ISSUE TITLE
Bug? in detail page large image title

### ISSUE THREAD

**Issue by Puppyknucks** [nbrightproject/NBrightBuy#74]
on the details page, when you click on the image and the window opens with the larger image only the first pictures image title shows, the other 3 pictures show a ‘2’ as the title but I have them all titled in the article details.

**Comment by leedavi** [comment]
Yes, I see that on the demo also, looks like a bug in the ClassicRazor template.  I'll look into this, thx for reporting it.

**Comment by leedavi** [comment]
In NBS_ProductDisplayDetail.cshtml

replace (line 72)

   img src="/DesktopModules/NBright/NBrightBuy/NBrightThumb.ashx?src=@(img.GetXmlProperty("genxml/hidden/imageurl"))&amp;w=70&amp;h=0" alt="2" title=""

with

```
<img src="/DesktopModules/NBright/NBrightBuy/NBrightThumb.ashx?src=@(img.GetXmlProperty("genxml/hidden/imageurl"))&amp;w=70&amp;h=0" alt="@(img.GetXmlProperty("genxml/textbox/txtimagedesc"))" title="">
```

**Comment by Puppyknucks** [comment]
That fixed it, thanks!
