### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by dekaleict** [nbrightproject/NBrightBuy#76]
Is there a way to update the stock via SQL ? I have to connect to an ERP and want to update latest stock info via SQL.

**Comment by leedavi** [comment]
Yes, this is possible, but the data is stored in a XML field, so you'll need to use XML DML

https://msdn.microsoft.com/en-us/library/ms190675.aspx

If you look at the NBrightBuy table, in there you'll find records with a TypeCode = 'PRD', these records are the product data.   You'll need to update the stock nodes in the model node.
......

```
<models>
    <genxml>
      <files />
      <hidden>
        <modelid>19</modelid>
      </hidden>
      <textbox>
        <availabledate datatype="date" />
        <txtqtyminstock>0</txtqtyminstock>
        <txtmodelref>etrivconf</txtmodelref>
        <txtunitcost>125.00</txtunitcost>
        <txtsaleprice>0.00</txtsaleprice>
        <txtbarcode />
        **<txtqtyremaining>-1</txtqtyremaining>**
        <txtqtystockset>0</txtqtystockset>
        <txtdealercost>0.00</txtdealercost>
        <txtpurchasecost>0.00</txtpurchasecost>
        <weight>1</weight>
        <depth>0</depth>
        <width>0</width>
        <height>0</height>
        <unit />
        <delay />
      </textbox>
      <checkbox>
        <chkstockon>False</chkstockon>
        <chkishidden>False</chkishidden>
        <chkdeleted>False</chkdeleted>
        <chkdealeronly>False</chkdealeronly>
      </checkbox>
      <dropdownlist>
        <modelstatus>010</modelstatus>
      </dropdownlist>
      <checkboxlist />
      <radiobuttonlist />
    </genxml>
  </models>
```

.......

I think the "txtqtyremaining" node is the value you'll need to update, the other fields are to calc percentage of stock and minimum required in stock.  

there also may be more than 1 model for each product.

**Comment by leedavi** [comment]
One other thing, NBS uses serverside caching for the data, so when you alter the value in the DB through SQL, the result may not be seen on the frontoffice until the cache is cleared.

**Comment by dekaleict** [comment]
Thanks for the information. I've got it done with this SQL Query where '999' is the new Stock, and '125' is the productid.

UPDATE NBrightBuy
SET XMLData.modify('replace value of (/genxml/models/genxml/textbox/txtqtyremaining[1]/text())[1] with "999"') 
WHERE (TypeCode = 'PRD') AND (ItemID='125')
