### ISSUE TITLE
How to get overview of available properties: @info.GetXmlProperty

### ISSUE THREAD

**Issue by dekaleict** [nbrightproject/NBrightBuy#77]
Is there an overview wich properties i can get using this 
@info.GetXmlProperty(".....")

And if i added a supplier as property (via group property) how to show the value of the choosen one in a productdetailview?

**Comment by leedavi** [comment]
The GetXmlProperty() method takes any xpath and returns the value.  So if you look at the DB you'll see the XML struture.  For mulitple lanaguges you have a "*LANG" typecode field, this contains the localized fields and when passed to the template as a class, these localized fields are put in e <lang> node for the langauge being viewed.

So you get:
@info.GetXmlProperty("genxml/lang/genxml/textbox/txtproductname")

and for non-localized fields:
@info.GetXmlProperty("genxml/textbox/txtproductref")

For proerties you need to use a token.  @PropertyValue(...)

You can find out what these tokens are by looking at the code...

https://github.com/nbrightproject/NBrightBuy/blob/master/render/NBrightBuyRazorTokens.cs

I'm trying to find time to document all this!
