### ISSUE TITLE
Related Items Sizing (Razor Template)

### ISSUE THREAD

**Issue by qualitymanager** [nbrightproject/NBrightBuy#79]
I'm looking at sizing of the related items and the default template appears to be using the settings from the List Items section of settings screen not the related items settings, am i correct in this assumption?

If i am can you post up a replacement  section of the productDisplayDetail.cshtml as i would like to be able to have different size Related Items and List Items

I swapped the settings values in all the GetSettings() from the "classic<x>" to "related<x>" ones in the template but it appears to still be using ListItemWidth for item spacing and i cant see it mentioned in the template so this will also need looking at.

**Comment by leedavi** [comment]
The easy way is just to edit line 352 and hardcode the values you want..

```
                                <img title="@(info.GetXmlProperty("genxml/lang/genxml/textbox/txtsummary"))" src="@ProductImage(rp, Model.GetSetting("classicthumbnailwidth"), Model.GetSetting("classicthumbnailheight"))">
```

to...

```
                                <img title="@(info.GetXmlProperty("genxml/lang/genxml/textbox/txtsummary"))" src="@ProductImage(rp, 100, 0)">
```

If you put the template it in the portal root with the same path as in desktopmodules, you'll only change it in that portal.  Or you could create a new theme folder at desktopmodule level and copy your changed template into that and in the product list settings point it to you new theme, it will take your template and all other templates will default to classicrazor.

**Comment by qualitymanager** [comment]
perhaps a mis-understanding, the default classicrazor template is incorrect.

All related item settings are being ignored in the installed classic razor temlate

**Comment by leedavi** [comment]
OK I see, the templates not using the correct settings.

It should be something like this:

`                    <div class="product" style="width: @Model.GetSetting("relateditemwidth")px; height: @Model.GetSetting("relateditemheight"); margin-bottom: @Model.GetSetting("relateditembottommargin")px">

```
                    <div class="productimg" style="width: 294px; height: @(Model.GetSetting("relateditemimagecontainerheight"))">

                        @if (rp.GetXmlProperty("genxml/imgs/genxml[1]/hidden/imageurl") != "")
                        {
                            <div class="image" style="height: @(Model.GetSetting("relateditemimagecontainerheight"))">
                                <img title="@(info.GetXmlProperty("genxml/lang/genxml/textbox/txtsummary"))" src="@ProductImage(rp, Model.GetSetting("relatedimagewidth"), Model.GetSetting("relatedimageheight"))">
                            </div>
                        }
                        else
                        {
                            <div class="noimage" style="height: @(Model.GetSetting("relateditemimagecontainerheight"))">
                                @(Model.GetSettingHtmlOf("noimageicon"))
                            </div>
                        }
                    </div>
```

</div>
`

I've updated this for the next release.
