### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by SzekelyVegan** [nbrightproject/NBrightBuy#8]
After I installed the PayPal plugin, I get an "Illegal characters in path" error message on the basket/checkout page.
I did put in 2 settings in BO> Admin> Paypal Payment, the verifyURL and PayPal ID - first I used my paypal email for ID then I tried the Merchant account ID from my paypal account, same results.

**Comment by SzekelyVegan** [comment]
If I go to the Payment page the Pay Now button is there and I can place the order.

**Comment by leedavi** [comment]
have you gone into the back office and saved the PayPal setting?
