### ISSUE TITLE
Can't see products and catagories from other portals in dnn installation

### ISSUE THREAD

**Issue by Puppyknucks** [nbrightproject/NBrightBuy#83]
I have checked the share products option in the back office but I cannot see anything from my other sites. do I need to something more?

**Comment by leedavi** [comment]
You need to create that option before you create articles for a portal, after activating it all products created in that portal will be visible to other portals.

I you need to have the products you've created before visible to all portals, you need to updated the DB but changing the PortalID to -1 for all PRD typecode records, do this in the NBrightBuy table.

**Comment by Tychodewaard** [comment]
What also might help: Hit the Validate (in Back office: admin-tools) button in the main store. This will push all products and categories to the other stores. Then clear the cache of the substore and your products are there. 

Mind you 1: if you have created products in the sub portals, these products will be overwritten.
Mind you 2: if you hit the validate button in the sub portal by accident, all products and categories from the main store will be gone. This might scare you the first time this accident happens. Just hit tha validate in the main store again, clear the cache and you're good to go.

**Comment by leedavi** [comment]
Tyco, the validation does NOT remove or overwrite any products or categories. I think you are seeing the results of it removing duplicated/corrupt category xref records, which might make it seem like it does.

The validation will not alter the products already created in a portal, for that you need to run some SQL on the DB.
