### ISSUE TITLE
Catagory menu settings not saving

### ISSUE THREAD

**Issue by Puppyknucks** [nbrightproject/NBrightBuy#84]
On a new site using the NB template, the catagorymenu module on the online store page will not save classic razor as the theme and is saying 'no module settings' when viewing the page. I was able to change the module title and module container and everything saves the changes.
I have deleted and reinstalled the module and the same problem exists.

**Comment by leedavi** [comment]
Not heard of this problem before.  Have you got any errors in the DNN event log or any JS errors on the page?

**Comment by Puppyknucks** [comment]
this error popped up on the home page but otherwise everything seems ok.
Could Not Load Theme: /Portals/_default/Skins/DnnBootster/Home.ascx, Error: The file '/Portals/_default/Skins/DnnBootster/Home.ascx' does not exist.
