### ISSUE TITLE
Module Title from Product Title

### ISSUE THREAD

**Issue by qualitymanager** [nbrightproject/NBrightBuy#85]
The old nbstore had the option to set the module title from the category name, product title, category+product name, can you tell me where these options are when razor templates are selected?

If they dont exist could you tell me how to achieve the same result as the product title option.

**Comment by leedavi** [comment]
These option don't exist, the idea is the razor template can deal with all display.

There are 2 tokens that can help to do this. Although you've always got the problem that a product can be in multiple categories. 

@CategoryBreadCrumb

 CategoryBreadCrumb(Boolean includelinks, NBrightRazor model, Boolean aslist = true, int tabRedirect = -1, String separator = "", int wordlength = -1, int maxlength = 400)

and 

@ProductName

ProductName(NBrightInfo info)

**Comment by qualitymanager** [comment]
I was thinking more of the DNN Module title (so it shows in the modules container title.
I will come back to this as i have a bigger problem today, i will raise it seperatly.

**Comment by leedavi** [comment]
In this case just use a DNN container that displays the module title, this isn't controlled by NBS.
