### ISSUE TITLE
Payments and checkout process

### ISSUE THREAD

**Issue by Puppyknucks** [nbrightproject/NBrightBuy#86]
With paypal payments installed how can I disable manual payments? 

Since paypal provides the buyers address and contact information with payment is there a way to skip the 'Addresses' portion of checkout? It would remove redundancy and speedup checkout.

Is there a way to not make a buyer register on the site in order to buy? Checkout as guest type of checkout? I personally hate registering places and filling out endless pages to buy something..

**Comment by leedavi** [comment]
Turn off manual payment in the >BO>Admin>Plugins

You turn off the registration by changing the page permissions, that's all controlled by DNN, NBS doesn't care.

**Comment by Puppyknucks** [comment]
On a new dnn portal using the nBrightbuy theme after adding an item to the basket then you click next to enter an address, instead of going to the address, I am thrown to the recycle bin and if I am not logged in it throws me to a login page even though I have the permissions set for all users.

**Comment by Puppyknucks** [comment]
when I walk thru checkout and go to payment I am showing 2 paypal options and both pay now buttons go to a white screen saying "The service is unavailable".

**Comment by leedavi** [comment]
have you got it activated 2 times int he plugins?

**Comment by Puppyknucks** [comment]
there is only 1 paypal occurrence in the plugins
![double paypal](https://cloud.githubusercontent.com/assets/22919237/19979344/1bba82e6-a1c8-11e6-9545-7fc117ca975d.JPG)

**Comment by Puppyknucks** [comment]
Manual Payments was active but for whatever reason it was showing as a second paypal.  I deactivated manual payments and the paypal button is now functioning .
![double paypal](https://cloud.githubusercontent.com/assets/22919237/19979793/bb951a50-a1c9-11e6-9b20-b523697fde92.JPG)
