### ISSUE TITLE
How to add options for product display so that would be displayed as radio buttons?

### ISSUE THREAD

**Issue by justina1206** [nbrightproject/NBrightBuy#97]
How to add options for product display so that would be displayed as radio buttons?

At the moment it displqayes as select options(drop down) or checkboxes?

Thank you fore yopur help in advance

**Comment by leedavi** [comment]
You can display the model ina radiobutton using the @ModelRadio token, but cannot do that with options, at the moment the display token is only coded to use a dropdown.
