### ISSUE TITLE
Inventory Control?

### ISSUE THREAD

**Issue by in8dna** [nbrightproject/NBrightBuy#98]
Where can I learn how to use any inventory control? I've checked the docs, and think I've scoured the store back office settings... 

I see the [  ]ACTIVATE STOCK checkbox in the MODELS section of the product editing, but I can't find a place to enter the 'quantity on hand' 

Pointers?

**Comment by leedavi** [comment]
The stock is activated on a model by model basis.  

If you look at the product model you'll see a activate stock option.

It a very simple stock control and the status gets adjusted during purchase, based on the stock and minimum stock levels.  The other fields are used for display purpose in special use case where stock is more important, but are not used in the default templates.

![capture](https://cloud.githubusercontent.com/assets/5583141/19956313/5cdb8550-a18b-11e6-930b-dfe18a29b2f6.PNG)

P.S. we are trying to improve the documentation.

**Comment by in8dna** [comment]
Thanks for the screen shot. How do we get the bottom row of text boxes to display?

![image](https://cloud.githubusercontent.com/assets/13932030/19987142/d8e189e2-a1d6-11e6-8391-e44a4a2002f9.png)

**Comment by leedavi** [comment]
You've got a problem there!  The row should appear when you check the activate stock check box, it uses JS to do this.  
Have you got any JS errors on the page?  And what verison of NBS are you using?

I've never seen this not work!

If you PM me a login I'll take a look for you.
