### ISSUE TITLE
Minimum Sale Amount Configuration

### ISSUE THREAD

**Issue by in8dna** [nbrightproject/NBrightBuy#99]
How should we configure products or the store so that items that are 'BONUS' (free) with a minimum $20 purchase can STOP people from ordering the 'BONUS' item without meeting the minimum purchase amount?

We have hundreds of 'BONUS' items that a buyer can get shipped in their order so long as the buy $20. Lots of people are adding the items to their purchase or $2 or $3. The goal is to have a minimum total before they can checkout.

Ideas?

![image](https://cloud.githubusercontent.com/assets/13932030/19987458/82463a36-a1d8-11e6-9d01-48c989dd6a38.png)

**Comment by leedavi** [comment]
I think this would need a special promotional plugin creating.  There is nothing in the default store that does this.

**Comment by in8dna** [comment]
What do you think the cost would be to build this?

 http://intelligentnetware.com/about.aspx 

Daniel Comp
210  557 4779   PST  
Co-Founder and CDO

 http://intelligentnetware.com/ 
Intelligent Netware™ : 
Seven IT Production World Records
Two-time SBA 'Champion-of-the-Year' winner
